// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merchant.proto

/*
Package Aphro_Merchant_pb is a generated protocol buffer package.

It is generated from these files:
	merchant.proto

It has these top-level messages:
	MerchantWaiterInfo
	MerchantWaiterCreateRequest
	MerchantWaiterCreateResponse
	MerchantWaiterDeleteRequest
	MerchantWaiterDeleteResponse
	MerchantRoomInfoRequest
	MerchantRoomInfoResponse
	MerchantOpenRequest
	MerchantOpenResponse
	MerchantRegisterRequest
	MerchantRegisterResponse
	MerchantChangePswRequest
	MerchantChangePswResponse
	MerchantLoginRequest
	MerchantLoginResponse
	MerchantInfoRequest
	InnerMerchantAccount
	MerchantInfoResponse
	MerchantSendCodeRequest
	MerchantSendCodeResponse
	MerchantVerifyCodeRequest
	MerchantVerifyCodeResponse
*/
package Aphro_Merchant_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import Aphro_CommonBiz "CommonBiz/Response/PB"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MerchantWaiterInfo struct {
	Name    string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ImageID float64 `protobuf:"fixed64,2,opt,name=imageID" json:"imageID,omitempty"`
}

func (m *MerchantWaiterInfo) Reset()                    { *m = MerchantWaiterInfo{} }
func (m *MerchantWaiterInfo) String() string            { return proto.CompactTextString(m) }
func (*MerchantWaiterInfo) ProtoMessage()               {}
func (*MerchantWaiterInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MerchantWaiterInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantWaiterInfo) GetImageID() float64 {
	if m != nil {
		return m.ImageID
	}
	return 0
}

type MerchantWaiterCreateRequest struct {
	Token      string              `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MerchantID string              `protobuf:"bytes,2,opt,name=merchantID" json:"merchantID,omitempty"`
	Waiter     *MerchantWaiterInfo `protobuf:"bytes,3,opt,name=waiter" json:"waiter,omitempty"`
}

func (m *MerchantWaiterCreateRequest) Reset()                    { *m = MerchantWaiterCreateRequest{} }
func (m *MerchantWaiterCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantWaiterCreateRequest) ProtoMessage()               {}
func (*MerchantWaiterCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MerchantWaiterCreateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MerchantWaiterCreateRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *MerchantWaiterCreateRequest) GetWaiter() *MerchantWaiterInfo {
	if m != nil {
		return m.Waiter
	}
	return nil
}

type MerchantWaiterCreateResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantWaiterCreateResponse) Reset()                    { *m = MerchantWaiterCreateResponse{} }
func (m *MerchantWaiterCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantWaiterCreateResponse) ProtoMessage()               {}
func (*MerchantWaiterCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MerchantWaiterCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantWaiterDeleteRequest struct {
	Token      string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MerchantID string `protobuf:"bytes,2,opt,name=merchantID" json:"merchantID,omitempty"`
	Waiterid   uint64 `protobuf:"varint,3,opt,name=waiterid" json:"waiterid,omitempty"`
}

func (m *MerchantWaiterDeleteRequest) Reset()                    { *m = MerchantWaiterDeleteRequest{} }
func (m *MerchantWaiterDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantWaiterDeleteRequest) ProtoMessage()               {}
func (*MerchantWaiterDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MerchantWaiterDeleteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MerchantWaiterDeleteRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *MerchantWaiterDeleteRequest) GetWaiterid() uint64 {
	if m != nil {
		return m.Waiterid
	}
	return 0
}

type MerchantWaiterDeleteResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantWaiterDeleteResponse) Reset()                    { *m = MerchantWaiterDeleteResponse{} }
func (m *MerchantWaiterDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantWaiterDeleteResponse) ProtoMessage()               {}
func (*MerchantWaiterDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MerchantWaiterDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantRoomInfoRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID       uint32 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *MerchantRoomInfoRequest) Reset()                    { *m = MerchantRoomInfoRequest{} }
func (m *MerchantRoomInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantRoomInfoRequest) ProtoMessage()               {}
func (*MerchantRoomInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MerchantRoomInfoRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *MerchantRoomInfoRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type MerchantRoomInfoResponse struct {
	Reverse string `protobuf:"bytes,1,opt,name=reverse" json:"reverse,omitempty"`
}

func (m *MerchantRoomInfoResponse) Reset()                    { *m = MerchantRoomInfoResponse{} }
func (m *MerchantRoomInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantRoomInfoResponse) ProtoMessage()               {}
func (*MerchantRoomInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MerchantRoomInfoResponse) GetReverse() string {
	if m != nil {
		return m.Reverse
	}
	return ""
}

type MerchantOpenRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Cellphone  string `protobuf:"bytes,2,opt,name=cellphone" json:"cellphone,omitempty"`
	Address    string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	PaymentBit uint32 `protobuf:"varint,4,opt,name=paymentBit" json:"paymentBit,omitempty"`
}

func (m *MerchantOpenRequest) Reset()                    { *m = MerchantOpenRequest{} }
func (m *MerchantOpenRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantOpenRequest) ProtoMessage()               {}
func (*MerchantOpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MerchantOpenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantOpenRequest) GetCellphone() string {
	if m != nil {
		return m.Cellphone
	}
	return ""
}

func (m *MerchantOpenRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MerchantOpenRequest) GetPaymentBit() uint32 {
	if m != nil {
		return m.PaymentBit
	}
	return 0
}

type MerchantOpenResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantOpenResponse) Reset()                    { *m = MerchantOpenResponse{} }
func (m *MerchantOpenResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantOpenResponse) ProtoMessage()               {}
func (*MerchantOpenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MerchantOpenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantRegisterRequest struct {
	Key        string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Role       uint32 `protobuf:"varint,5,opt,name=role" json:"role,omitempty"`
	MerchantID uint32 `protobuf:"varint,6,opt,name=merchantID" json:"merchantID,omitempty"`
}

func (m *MerchantRegisterRequest) Reset()                    { *m = MerchantRegisterRequest{} }
func (m *MerchantRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantRegisterRequest) ProtoMessage()               {}
func (*MerchantRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MerchantRegisterRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MerchantRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantRegisterRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *MerchantRegisterRequest) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *MerchantRegisterRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

type MerchantRegisterResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantRegisterResponse) Reset()                    { *m = MerchantRegisterResponse{} }
func (m *MerchantRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantRegisterResponse) ProtoMessage()               {}
func (*MerchantRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MerchantRegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantChangePswRequest struct {
	NewPsw       string `protobuf:"bytes,1,opt,name=newPsw" json:"newPsw,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	VerifyCode   string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Cellphone    string `protobuf:"bytes,4,opt,name=cellphone" json:"cellphone,omitempty"`
}

func (m *MerchantChangePswRequest) Reset()                    { *m = MerchantChangePswRequest{} }
func (m *MerchantChangePswRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantChangePswRequest) ProtoMessage()               {}
func (*MerchantChangePswRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MerchantChangePswRequest) GetNewPsw() string {
	if m != nil {
		return m.NewPsw
	}
	return ""
}

func (m *MerchantChangePswRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *MerchantChangePswRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *MerchantChangePswRequest) GetCellphone() string {
	if m != nil {
		return m.Cellphone
	}
	return ""
}

type MerchantChangePswResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantChangePswResponse) Reset()                    { *m = MerchantChangePswResponse{} }
func (m *MerchantChangePswResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantChangePswResponse) ProtoMessage()               {}
func (*MerchantChangePswResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MerchantChangePswResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantLoginRequest struct {
	Key          string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	TokenRequest string `protobuf:"bytes,2,opt,name=tokenRequest" json:"tokenRequest,omitempty"`
	MerchantID   uint32 `protobuf:"varint,3,opt,name=merchantID" json:"merchantID,omitempty"`
}

func (m *MerchantLoginRequest) Reset()                    { *m = MerchantLoginRequest{} }
func (m *MerchantLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantLoginRequest) ProtoMessage()               {}
func (*MerchantLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MerchantLoginRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MerchantLoginRequest) GetTokenRequest() string {
	if m != nil {
		return m.TokenRequest
	}
	return ""
}

func (m *MerchantLoginRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

type MerchantLoginResponse struct {
	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	Success      bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantLoginResponse) Reset()                    { *m = MerchantLoginResponse{} }
func (m *MerchantLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantLoginResponse) ProtoMessage()               {}
func (*MerchantLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MerchantLoginResponse) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *MerchantLoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantInfoRequest struct {
	Token      string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MerchantID string `protobuf:"bytes,2,opt,name=merchantID" json:"merchantID,omitempty"`
}

func (m *MerchantInfoRequest) Reset()                    { *m = MerchantInfoRequest{} }
func (m *MerchantInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantInfoRequest) ProtoMessage()               {}
func (*MerchantInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MerchantInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MerchantInfoRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

type InnerMerchantAccount struct {
	Role uint32 `protobuf:"varint,1,opt,name=role" json:"role,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *InnerMerchantAccount) Reset()                    { *m = InnerMerchantAccount{} }
func (m *InnerMerchantAccount) String() string            { return proto.CompactTextString(m) }
func (*InnerMerchantAccount) ProtoMessage()               {}
func (*InnerMerchantAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *InnerMerchantAccount) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *InnerMerchantAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MerchantInfoResponse struct {
	MerchantName    string                `protobuf:"bytes,1,opt,name=merchantName" json:"merchantName,omitempty"`
	MerchantAccount *InnerMerchantAccount `protobuf:"bytes,2,opt,name=merchantAccount" json:"merchantAccount,omitempty"`
}

func (m *MerchantInfoResponse) Reset()                    { *m = MerchantInfoResponse{} }
func (m *MerchantInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantInfoResponse) ProtoMessage()               {}
func (*MerchantInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *MerchantInfoResponse) GetMerchantName() string {
	if m != nil {
		return m.MerchantName
	}
	return ""
}

func (m *MerchantInfoResponse) GetMerchantAccount() *InnerMerchantAccount {
	if m != nil {
		return m.MerchantAccount
	}
	return nil
}

type MerchantSendCodeRequest struct {
	Cellphone string `protobuf:"bytes,1,opt,name=cellphone" json:"cellphone,omitempty"`
	Scene     uint32 `protobuf:"varint,2,opt,name=scene" json:"scene,omitempty"`
}

func (m *MerchantSendCodeRequest) Reset()                    { *m = MerchantSendCodeRequest{} }
func (m *MerchantSendCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantSendCodeRequest) ProtoMessage()               {}
func (*MerchantSendCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *MerchantSendCodeRequest) GetCellphone() string {
	if m != nil {
		return m.Cellphone
	}
	return ""
}

func (m *MerchantSendCodeRequest) GetScene() uint32 {
	if m != nil {
		return m.Scene
	}
	return 0
}

type MerchantSendCodeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantSendCodeResponse) Reset()                    { *m = MerchantSendCodeResponse{} }
func (m *MerchantSendCodeResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantSendCodeResponse) ProtoMessage()               {}
func (*MerchantSendCodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *MerchantSendCodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MerchantVerifyCodeRequest struct {
	Cellphone string `protobuf:"bytes,1,opt,name=cellphone" json:"cellphone,omitempty"`
	Scene     uint32 `protobuf:"varint,2,opt,name=scene" json:"scene,omitempty"`
	SmsCode   string `protobuf:"bytes,3,opt,name=smsCode" json:"smsCode,omitempty"`
}

func (m *MerchantVerifyCodeRequest) Reset()                    { *m = MerchantVerifyCodeRequest{} }
func (m *MerchantVerifyCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*MerchantVerifyCodeRequest) ProtoMessage()               {}
func (*MerchantVerifyCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MerchantVerifyCodeRequest) GetCellphone() string {
	if m != nil {
		return m.Cellphone
	}
	return ""
}

func (m *MerchantVerifyCodeRequest) GetScene() uint32 {
	if m != nil {
		return m.Scene
	}
	return 0
}

func (m *MerchantVerifyCodeRequest) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type MerchantVerifyCodeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *MerchantVerifyCodeResponse) Reset()                    { *m = MerchantVerifyCodeResponse{} }
func (m *MerchantVerifyCodeResponse) String() string            { return proto.CompactTextString(m) }
func (*MerchantVerifyCodeResponse) ProtoMessage()               {}
func (*MerchantVerifyCodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *MerchantVerifyCodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MerchantWaiterInfo)(nil), "Aphro.Merchant.pb.MerchantWaiterInfo")
	proto.RegisterType((*MerchantWaiterCreateRequest)(nil), "Aphro.Merchant.pb.MerchantWaiterCreateRequest")
	proto.RegisterType((*MerchantWaiterCreateResponse)(nil), "Aphro.Merchant.pb.MerchantWaiterCreateResponse")
	proto.RegisterType((*MerchantWaiterDeleteRequest)(nil), "Aphro.Merchant.pb.MerchantWaiterDeleteRequest")
	proto.RegisterType((*MerchantWaiterDeleteResponse)(nil), "Aphro.Merchant.pb.MerchantWaiterDeleteResponse")
	proto.RegisterType((*MerchantRoomInfoRequest)(nil), "Aphro.Merchant.pb.MerchantRoomInfoRequest")
	proto.RegisterType((*MerchantRoomInfoResponse)(nil), "Aphro.Merchant.pb.MerchantRoomInfoResponse")
	proto.RegisterType((*MerchantOpenRequest)(nil), "Aphro.Merchant.pb.MerchantOpenRequest")
	proto.RegisterType((*MerchantOpenResponse)(nil), "Aphro.Merchant.pb.MerchantOpenResponse")
	proto.RegisterType((*MerchantRegisterRequest)(nil), "Aphro.Merchant.pb.MerchantRegisterRequest")
	proto.RegisterType((*MerchantRegisterResponse)(nil), "Aphro.Merchant.pb.MerchantRegisterResponse")
	proto.RegisterType((*MerchantChangePswRequest)(nil), "Aphro.Merchant.pb.MerchantChangePswRequest")
	proto.RegisterType((*MerchantChangePswResponse)(nil), "Aphro.Merchant.pb.MerchantChangePswResponse")
	proto.RegisterType((*MerchantLoginRequest)(nil), "Aphro.Merchant.pb.MerchantLoginRequest")
	proto.RegisterType((*MerchantLoginResponse)(nil), "Aphro.Merchant.pb.MerchantLoginResponse")
	proto.RegisterType((*MerchantInfoRequest)(nil), "Aphro.Merchant.pb.MerchantInfoRequest")
	proto.RegisterType((*InnerMerchantAccount)(nil), "Aphro.Merchant.pb.InnerMerchantAccount")
	proto.RegisterType((*MerchantInfoResponse)(nil), "Aphro.Merchant.pb.MerchantInfoResponse")
	proto.RegisterType((*MerchantSendCodeRequest)(nil), "Aphro.Merchant.pb.MerchantSendCodeRequest")
	proto.RegisterType((*MerchantSendCodeResponse)(nil), "Aphro.Merchant.pb.MerchantSendCodeResponse")
	proto.RegisterType((*MerchantVerifyCodeRequest)(nil), "Aphro.Merchant.pb.MerchantVerifyCodeRequest")
	proto.RegisterType((*MerchantVerifyCodeResponse)(nil), "Aphro.Merchant.pb.MerchantVerifyCodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MerchantService service

type MerchantServiceClient interface {
	// 商户开户
	MerchantOpen(ctx context.Context, in *MerchantOpenRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 商户用户注册
	MerchantRegister(ctx context.Context, in *MerchantRegisterRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 商户用户修改密码
	MerchantChangePsw(ctx context.Context, in *MerchantChangePswRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 商户app登陆
	MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 商户app 信息
	MerchantInfo(ctx context.Context, in *MerchantInfoRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 商户app 信息
	MerchantRoomInfo(ctx context.Context, in *MerchantRoomInfoRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 新增商户服务信息
	MerchantWaiterCreate(ctx context.Context, in *MerchantWaiterCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 删除商户服务信息
	MerchantWaiterDelete(ctx context.Context, in *MerchantWaiterDeleteRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 短信验证码 验证接口
	MerchantVerifyCode(ctx context.Context, in *MerchantVerifyCodeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 短信验证码 发送接口
	MerchantSendCode(ctx context.Context, in *MerchantSendCodeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
}

type merchantServiceClient struct {
	cc *grpc.ClientConn
}

func NewMerchantServiceClient(cc *grpc.ClientConn) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) MerchantOpen(ctx context.Context, in *MerchantOpenRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantOpen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantRegister(ctx context.Context, in *MerchantRegisterRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantChangePsw(ctx context.Context, in *MerchantChangePswRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantChangePsw", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantInfo(ctx context.Context, in *MerchantInfoRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantRoomInfo(ctx context.Context, in *MerchantRoomInfoRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantRoomInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantWaiterCreate(ctx context.Context, in *MerchantWaiterCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantWaiterCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantWaiterDelete(ctx context.Context, in *MerchantWaiterDeleteRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantWaiterDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantVerifyCode(ctx context.Context, in *MerchantVerifyCodeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantVerifyCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantSendCode(ctx context.Context, in *MerchantSendCodeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantSendCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MerchantService service

type MerchantServiceServer interface {
	// 商户开户
	MerchantOpen(context.Context, *MerchantOpenRequest) (*Aphro_CommonBiz.Response, error)
	// 商户用户注册
	MerchantRegister(context.Context, *MerchantRegisterRequest) (*Aphro_CommonBiz.Response, error)
	// 商户用户修改密码
	MerchantChangePsw(context.Context, *MerchantChangePswRequest) (*Aphro_CommonBiz.Response, error)
	// 商户app登陆
	MerchantLogin(context.Context, *MerchantLoginRequest) (*Aphro_CommonBiz.Response, error)
	// 商户app 信息
	MerchantInfo(context.Context, *MerchantInfoRequest) (*Aphro_CommonBiz.Response, error)
	// 商户app 信息
	MerchantRoomInfo(context.Context, *MerchantRoomInfoRequest) (*Aphro_CommonBiz.Response, error)
	// 新增商户服务信息
	MerchantWaiterCreate(context.Context, *MerchantWaiterCreateRequest) (*Aphro_CommonBiz.Response, error)
	// 删除商户服务信息
	MerchantWaiterDelete(context.Context, *MerchantWaiterDeleteRequest) (*Aphro_CommonBiz.Response, error)
	// 短信验证码 验证接口
	MerchantVerifyCode(context.Context, *MerchantVerifyCodeRequest) (*Aphro_CommonBiz.Response, error)
	// 短信验证码 发送接口
	MerchantSendCode(context.Context, *MerchantSendCodeRequest) (*Aphro_CommonBiz.Response, error)
}

func RegisterMerchantServiceServer(s *grpc.Server, srv MerchantServiceServer) {
	s.RegisterService(&_MerchantService_serviceDesc, srv)
}

func _MerchantService_MerchantOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantOpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantOpen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantOpen(ctx, req.(*MerchantOpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantRegister(ctx, req.(*MerchantRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantChangePsw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantChangePswRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantChangePsw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantChangePsw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantChangePsw(ctx, req.(*MerchantChangePswRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantLogin(ctx, req.(*MerchantLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantInfo(ctx, req.(*MerchantInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantRoomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantRoomInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantRoomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantRoomInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantRoomInfo(ctx, req.(*MerchantRoomInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantWaiterCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantWaiterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantWaiterCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantWaiterCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantWaiterCreate(ctx, req.(*MerchantWaiterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantWaiterDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantWaiterDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantWaiterDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantWaiterDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantWaiterDelete(ctx, req.(*MerchantWaiterDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantVerifyCode(ctx, req.(*MerchantVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantSendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantSendCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantSendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantSendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantSendCode(ctx, req.(*MerchantSendCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Aphro.Merchant.pb.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "merchantOpen",
			Handler:    _MerchantService_MerchantOpen_Handler,
		},
		{
			MethodName: "merchantRegister",
			Handler:    _MerchantService_MerchantRegister_Handler,
		},
		{
			MethodName: "merchantChangePsw",
			Handler:    _MerchantService_MerchantChangePsw_Handler,
		},
		{
			MethodName: "merchantLogin",
			Handler:    _MerchantService_MerchantLogin_Handler,
		},
		{
			MethodName: "merchantInfo",
			Handler:    _MerchantService_MerchantInfo_Handler,
		},
		{
			MethodName: "merchantRoomInfo",
			Handler:    _MerchantService_MerchantRoomInfo_Handler,
		},
		{
			MethodName: "merchantWaiterCreate",
			Handler:    _MerchantService_MerchantWaiterCreate_Handler,
		},
		{
			MethodName: "merchantWaiterDelete",
			Handler:    _MerchantService_MerchantWaiterDelete_Handler,
		},
		{
			MethodName: "merchantVerifyCode",
			Handler:    _MerchantService_MerchantVerifyCode_Handler,
		},
		{
			MethodName: "merchantSendCode",
			Handler:    _MerchantService_MerchantSendCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}

func init() { proto.RegisterFile("merchant.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 948 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x6f, 0x1c, 0x35,
	0x14, 0xd6, 0x6c, 0x92, 0xa5, 0x39, 0x4d, 0x9a, 0xd6, 0x59, 0x9a, 0xcd, 0x12, 0x42, 0x64, 0x01,
	0x8d, 0x02, 0xda, 0x41, 0xe1, 0x22, 0x54, 0x09, 0xa4, 0x26, 0x7d, 0x89, 0xa0, 0x10, 0x06, 0x0a,
	0xcf, 0xd3, 0xd9, 0x93, 0xcd, 0xa8, 0x3b, 0xf6, 0x62, 0x4f, 0x12, 0xd2, 0x0a, 0x24, 0x90, 0x78,
	0xe4, 0x85, 0xf2, 0xcf, 0x78, 0xe4, 0x95, 0x1f, 0x82, 0xec, 0xb1, 0xd7, 0x9e, 0x0b, 0xb3, 0x69,
	0xf3, 0x66, 0x5b, 0x7b, 0xce, 0xf7, 0x7d, 0xe7, 0x36, 0x67, 0xe1, 0x56, 0x86, 0x22, 0x39, 0x8d,
	0x59, 0x3e, 0x9c, 0x0a, 0x9e, 0x73, 0x72, 0xe7, 0xc1, 0xf4, 0x54, 0xf0, 0xe1, 0xa3, 0xd9, 0xeb,
	0x93, 0xc1, 0xd6, 0x98, 0xf3, 0xf1, 0x04, 0xc3, 0x78, 0x9a, 0x86, 0x31, 0x63, 0x3c, 0x8f, 0xf3,
	0x94, 0x33, 0x59, 0x18, 0x0c, 0xde, 0x3e, 0xe4, 0x59, 0xc6, 0xd9, 0x41, 0xfa, 0x2c, 0x8c, 0x50,
	0x4e, 0x39, 0x93, 0x18, 0x1e, 0x1f, 0x84, 0xc2, 0x9c, 0x8b, 0x5f, 0xd1, 0x03, 0x20, 0xd6, 0xe5,
	0x0f, 0x71, 0x9a, 0xa3, 0x38, 0x62, 0x27, 0x9c, 0x10, 0x58, 0x64, 0x71, 0x86, 0xfd, 0x60, 0x27,
	0xd8, 0x5d, 0x8e, 0xf4, 0x99, 0xf4, 0xe1, 0xb5, 0x34, 0x8b, 0xc7, 0x78, 0xf4, 0xb0, 0xdf, 0xd9,
	0x09, 0x76, 0x83, 0xc8, 0x5e, 0xe9, 0x9f, 0x01, 0xbc, 0x51, 0x76, 0x72, 0x28, 0x30, 0xce, 0x31,
	0xc2, 0x1f, 0xcf, 0x50, 0xe6, 0xa4, 0x07, 0x4b, 0x39, 0x7f, 0x8a, 0xcc, 0xb8, 0x2b, 0x2e, 0x64,
	0x1b, 0xc0, 0x4a, 0x34, 0x2e, 0x97, 0x23, 0xef, 0x85, 0x7c, 0x06, 0xdd, 0x0b, 0xed, 0xac, 0xbf,
	0xb0, 0x13, 0xec, 0xde, 0xdc, 0x7f, 0x67, 0x58, 0x8b, 0xc0, 0xb0, 0x4e, 0x3d, 0x32, 0x46, 0xf4,
	0x53, 0xd8, 0x6a, 0xe6, 0x54, 0xc8, 0x57, 0x72, 0xe4, 0x59, 0x92, 0xa0, 0x94, 0x9a, 0xd6, 0x8d,
	0xc8, 0x5e, 0x29, 0xaf, 0xaa, 0x79, 0x88, 0x13, 0xbc, 0xae, 0x9a, 0x01, 0xdc, 0x28, 0x88, 0xa5,
	0x23, 0xad, 0x67, 0x31, 0x9a, 0xdd, 0xeb, 0x54, 0x2d, 0xe0, 0x5c, 0xaa, 0x8f, 0x61, 0xc3, 0x5a,
	0x46, 0x9c, 0x67, 0x3a, 0x00, 0x86, 0x26, 0x85, 0x15, 0x89, 0x52, 0xa6, 0x9c, 0x7d, 0xe7, 0xb1,
	0x2d, 0xbd, 0x91, 0xbb, 0xd0, 0x15, 0xca, 0xac, 0x20, 0xbc, 0x1a, 0x99, 0x1b, 0xfd, 0x08, 0xfa,
	0x75, 0xb7, 0x8e, 0x8c, 0xc0, 0x73, 0x14, 0xd2, 0x56, 0x87, 0xbd, 0xd2, 0x5f, 0x03, 0x58, 0xb7,
	0x66, 0x5f, 0x4f, 0x91, 0x59, 0x26, 0x4d, 0xc5, 0xb4, 0x05, 0xcb, 0x09, 0x4e, 0x26, 0xd3, 0x53,
	0xce, 0xd0, 0x44, 0xcb, 0x3d, 0x28, 0x8c, 0x78, 0x34, 0x12, 0x4a, 0xf0, 0x42, 0x81, 0x61, 0xae,
	0x2a, 0xcc, 0xd3, 0xf8, 0x32, 0x43, 0x96, 0x1f, 0xa4, 0x79, 0x7f, 0x51, 0xb3, 0xf6, 0x5e, 0xe8,
	0x07, 0xd0, 0x2b, 0x53, 0x98, 0x1b, 0xc2, 0x17, 0x81, 0x17, 0x43, 0x1c, 0xa7, 0x32, 0x47, 0x61,
	0x99, 0xdf, 0x86, 0x85, 0xa7, 0x78, 0x69, 0x88, 0xab, 0xe3, 0x4c, 0x4b, 0xc7, 0xd3, 0xb2, 0x0d,
	0x70, 0x8e, 0x22, 0x3d, 0xb9, 0x3c, 0xe4, 0x23, 0x34, 0x84, 0xbd, 0x17, 0x65, 0x23, 0xf8, 0x04,
	0xfb, 0x4b, 0x9a, 0xad, 0x3e, 0x57, 0xca, 0xa5, 0x5b, 0xe8, 0x70, 0x2f, 0xa5, 0x0c, 0xcc, 0x48,
	0xcd, 0xd5, 0xf2, 0x57, 0xe0, 0xcc, 0x0e, 0x4f, 0x63, 0x36, 0xc6, 0x63, 0x79, 0x61, 0xc5, 0xdc,
	0x85, 0x2e, 0xc3, 0x8b, 0x63, 0x79, 0x61, 0xf4, 0x98, 0x5b, 0xad, 0x50, 0x3a, 0x0d, 0x85, 0x32,
	0x4f, 0x62, 0x29, 0x9d, 0x8b, 0x95, 0x74, 0xd2, 0x8f, 0x61, 0xb3, 0x81, 0xd5, 0x5c, 0x35, 0x13,
	0x97, 0xcb, 0x2f, 0xf9, 0x38, 0x65, 0xff, 0x9f, 0x15, 0x0a, 0x2b, 0xba, 0x0b, 0xcd, 0x2f, 0xac,
	0x04, 0xff, 0xad, 0x12, 0xf1, 0x85, 0x5a, 0xc4, 0x1f, 0xc3, 0xeb, 0x15, 0x34, 0x43, 0xf0, 0x2a,
	0x8d, 0xe4, 0x89, 0xe8, 0x94, 0x45, 0x7c, 0xe1, 0x7a, 0xc2, 0xef, 0xce, 0x57, 0x1a, 0x22, 0xf4,
	0x73, 0xe8, 0x1d, 0x31, 0x86, 0xc2, 0x7a, 0x7c, 0x90, 0x24, 0xfc, 0x8c, 0xe5, 0xb3, 0x0a, 0x0b,
	0xbc, 0x0a, 0x6b, 0xa8, 0x54, 0xfa, 0x47, 0xe0, 0x42, 0x5a, 0x6a, 0x6a, 0x0a, 0x2b, 0x16, 0xe6,
	0x2b, 0xd7, 0xaa, 0xa5, 0x37, 0xf2, 0x0d, 0xac, 0x65, 0x65, 0x5c, 0xed, 0xfb, 0xe6, 0xfe, 0xbd,
	0x86, 0xc1, 0xdc, 0x44, 0x33, 0xaa, 0xda, 0xd3, 0x47, 0xae, 0xf5, 0xbe, 0x45, 0x36, 0x52, 0xa5,
	0x64, 0x03, 0x54, 0xaa, 0xa8, 0xa0, 0x3a, 0x20, 0x7a, 0xb0, 0x24, 0x13, 0x34, 0xa3, 0x63, 0x35,
	0x2a, 0x2e, 0x7e, 0xd3, 0x38, 0x77, 0x73, 0xcb, 0x2c, 0x75, 0xd5, 0xf9, 0xfd, 0xac, 0xa2, 0xaf,
	0x41, 0x43, 0x43, 0x65, 0xd2, 0xeb, 0x14, 0x7b, 0xa5, 0x9f, 0xc0, 0xa0, 0x09, 0x6a, 0x1e, 0xc5,
	0xfd, 0x7f, 0x96, 0x61, 0xcd, 0x29, 0x13, 0xe7, 0x69, 0x82, 0x64, 0xe2, 0x52, 0xa6, 0x26, 0x1d,
	0x79, 0xb7, 0xe5, 0xf3, 0xe8, 0x4d, 0xe3, 0xc1, 0xa6, 0xf9, 0xdd, 0x6c, 0x3b, 0x18, 0x5a, 0x02,
	0x74, 0xf3, 0xb7, 0xbf, 0xff, 0x7d, 0xd1, 0x59, 0xa7, 0xb7, 0x42, 0xeb, 0x39, 0xe4, 0x53, 0x64,
	0xf7, 0x83, 0x3d, 0xf2, 0x13, 0xdc, 0xce, 0x2a, 0xf3, 0x88, 0xec, 0xb5, 0x20, 0x56, 0x26, 0x69,
	0x1b, 0xea, 0x9b, 0x1a, 0x75, 0x83, 0x12, 0x87, 0x2a, 0x8c, 0xb5, 0x42, 0x7e, 0x0e, 0x77, 0xb2,
	0xea, 0xf0, 0x20, 0xef, 0xb5, 0x40, 0x57, 0x07, 0x5f, 0x1b, 0xf6, 0xb6, 0xc6, 0xee, 0xd3, 0x75,
	0x87, 0x9d, 0x58, 0x73, 0x05, 0xce, 0x61, 0x35, 0xf3, 0x87, 0x02, 0xb9, 0xd7, 0x02, 0xec, 0x0f,
	0xa9, 0x36, 0xd0, 0x81, 0x06, 0xed, 0xd1, 0x35, 0x07, 0x3a, 0x51, 0xa6, 0x0a, 0xd0, 0xcb, 0xaa,
	0x5e, 0xc4, 0xda, 0xb2, 0xea, 0xcd, 0x93, 0x97, 0xcc, 0x6a, 0xca, 0x4e, 0xb8, 0x42, 0x7b, 0xe6,
	0x65, 0xd5, 0x7c, 0xe7, 0xdb, 0xb3, 0x5a, 0xde, 0x31, 0xda, 0x50, 0xdf, 0xd2, 0xa8, 0x9b, 0x64,
	0xc3, 0xcb, 0x2a, 0xe7, 0x59, 0xf8, 0xbc, 0x58, 0x31, 0x7e, 0x26, 0xbf, 0x07, 0xd0, 0xcb, 0x1a,
	0x16, 0x34, 0x32, 0x9c, 0xbb, 0xe7, 0x95, 0xb6, 0xcb, 0x36, 0x12, 0x54, 0x93, 0xd8, 0xa2, 0x1e,
	0x89, 0x62, 0xe9, 0x0a, 0x13, 0xed, 0x42, 0xc5, 0xa0, 0xce, 0xa3, 0xd8, 0xbe, 0xae, 0xc0, 0xa3,
	0xb4, 0x17, 0xbe, 0x1a, 0x8f, 0x91, 0x76, 0xa1, 0x78, 0xfc, 0x02, 0x24, 0xab, 0xcd, 0x06, 0xf2,
	0x7e, 0x0b, 0x89, 0xda, 0xb4, 0xba, 0x42, 0x3e, 0x68, 0xcf, 0x51, 0x70, 0xdf, 0xef, 0x4a, 0x87,
	0xdb, 0xe1, 0xd9, 0x5a, 0x0b, 0x95, 0x81, 0xfd, 0x92, 0x1d, 0x2e, 0x8d, 0xf5, 0xfd, 0x60, 0xef,
	0x49, 0x57, 0xff, 0x13, 0xf9, 0xf0, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xfc, 0x76, 0x3b,
	0xf2, 0x0c, 0x00, 0x00,
}
