// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merchant.proto

package Aphro_Merchant_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MerchantWaiterInfor struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ImageID              float64  `protobuf:"fixed64,2,opt,name=imageID" json:"imageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantWaiterInfor) Reset()         { *m = MerchantWaiterInfor{} }
func (m *MerchantWaiterInfor) String() string { return proto.CompactTextString(m) }
func (*MerchantWaiterInfor) ProtoMessage()    {}
func (*MerchantWaiterInfor) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{0}
}
func (m *MerchantWaiterInfor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantWaiterInfor.Unmarshal(m, b)
}
func (m *MerchantWaiterInfor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantWaiterInfor.Marshal(b, m, deterministic)
}
func (dst *MerchantWaiterInfor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantWaiterInfor.Merge(dst, src)
}
func (m *MerchantWaiterInfor) XXX_Size() int {
	return xxx_messageInfo_MerchantWaiterInfor.Size(m)
}
func (m *MerchantWaiterInfor) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantWaiterInfor.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantWaiterInfor proto.InternalMessageInfo

func (m *MerchantWaiterInfor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantWaiterInfor) GetImageID() float64 {
	if m != nil {
		return m.ImageID
	}
	return 0
}

type MerchantWaiterCreateRequest struct {
	Token                string               `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MerchantID           string               `protobuf:"bytes,2,opt,name=merchantID" json:"merchantID,omitempty"`
	Waiter               *MerchantWaiterInfor `protobuf:"bytes,3,opt,name=waiter" json:"waiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MerchantWaiterCreateRequest) Reset()         { *m = MerchantWaiterCreateRequest{} }
func (m *MerchantWaiterCreateRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantWaiterCreateRequest) ProtoMessage()    {}
func (*MerchantWaiterCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{1}
}
func (m *MerchantWaiterCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantWaiterCreateRequest.Unmarshal(m, b)
}
func (m *MerchantWaiterCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantWaiterCreateRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantWaiterCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantWaiterCreateRequest.Merge(dst, src)
}
func (m *MerchantWaiterCreateRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantWaiterCreateRequest.Size(m)
}
func (m *MerchantWaiterCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantWaiterCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantWaiterCreateRequest proto.InternalMessageInfo

func (m *MerchantWaiterCreateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MerchantWaiterCreateRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *MerchantWaiterCreateRequest) GetWaiter() *MerchantWaiterInfor {
	if m != nil {
		return m.Waiter
	}
	return nil
}

type MerchantWaiterCreateRespone struct {
	Successed            bool     `protobuf:"varint,1,opt,name=successed" json:"successed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantWaiterCreateRespone) Reset()         { *m = MerchantWaiterCreateRespone{} }
func (m *MerchantWaiterCreateRespone) String() string { return proto.CompactTextString(m) }
func (*MerchantWaiterCreateRespone) ProtoMessage()    {}
func (*MerchantWaiterCreateRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{2}
}
func (m *MerchantWaiterCreateRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantWaiterCreateRespone.Unmarshal(m, b)
}
func (m *MerchantWaiterCreateRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantWaiterCreateRespone.Marshal(b, m, deterministic)
}
func (dst *MerchantWaiterCreateRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantWaiterCreateRespone.Merge(dst, src)
}
func (m *MerchantWaiterCreateRespone) XXX_Size() int {
	return xxx_messageInfo_MerchantWaiterCreateRespone.Size(m)
}
func (m *MerchantWaiterCreateRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantWaiterCreateRespone.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantWaiterCreateRespone proto.InternalMessageInfo

func (m *MerchantWaiterCreateRespone) GetSuccessed() bool {
	if m != nil {
		return m.Successed
	}
	return false
}

type MerchantWaiterDeleteRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MerchantID           string   `protobuf:"bytes,2,opt,name=merchantID" json:"merchantID,omitempty"`
	Waiterid             uint64   `protobuf:"varint,3,opt,name=waiterid" json:"waiterid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantWaiterDeleteRequest) Reset()         { *m = MerchantWaiterDeleteRequest{} }
func (m *MerchantWaiterDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantWaiterDeleteRequest) ProtoMessage()    {}
func (*MerchantWaiterDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{3}
}
func (m *MerchantWaiterDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantWaiterDeleteRequest.Unmarshal(m, b)
}
func (m *MerchantWaiterDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantWaiterDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantWaiterDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantWaiterDeleteRequest.Merge(dst, src)
}
func (m *MerchantWaiterDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantWaiterDeleteRequest.Size(m)
}
func (m *MerchantWaiterDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantWaiterDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantWaiterDeleteRequest proto.InternalMessageInfo

func (m *MerchantWaiterDeleteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MerchantWaiterDeleteRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *MerchantWaiterDeleteRequest) GetWaiterid() uint64 {
	if m != nil {
		return m.Waiterid
	}
	return 0
}

type MerchantWaiterDeleteRespone struct {
	Successed            bool     `protobuf:"varint,1,opt,name=successed" json:"successed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantWaiterDeleteRespone) Reset()         { *m = MerchantWaiterDeleteRespone{} }
func (m *MerchantWaiterDeleteRespone) String() string { return proto.CompactTextString(m) }
func (*MerchantWaiterDeleteRespone) ProtoMessage()    {}
func (*MerchantWaiterDeleteRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{4}
}
func (m *MerchantWaiterDeleteRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantWaiterDeleteRespone.Unmarshal(m, b)
}
func (m *MerchantWaiterDeleteRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantWaiterDeleteRespone.Marshal(b, m, deterministic)
}
func (dst *MerchantWaiterDeleteRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantWaiterDeleteRespone.Merge(dst, src)
}
func (m *MerchantWaiterDeleteRespone) XXX_Size() int {
	return xxx_messageInfo_MerchantWaiterDeleteRespone.Size(m)
}
func (m *MerchantWaiterDeleteRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantWaiterDeleteRespone.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantWaiterDeleteRespone proto.InternalMessageInfo

func (m *MerchantWaiterDeleteRespone) GetSuccessed() bool {
	if m != nil {
		return m.Successed
	}
	return false
}

type MerchantRoomInfoRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID               uint32   `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantRoomInfoRequest) Reset()         { *m = MerchantRoomInfoRequest{} }
func (m *MerchantRoomInfoRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantRoomInfoRequest) ProtoMessage()    {}
func (*MerchantRoomInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{5}
}
func (m *MerchantRoomInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantRoomInfoRequest.Unmarshal(m, b)
}
func (m *MerchantRoomInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantRoomInfoRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantRoomInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantRoomInfoRequest.Merge(dst, src)
}
func (m *MerchantRoomInfoRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantRoomInfoRequest.Size(m)
}
func (m *MerchantRoomInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantRoomInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantRoomInfoRequest proto.InternalMessageInfo

func (m *MerchantRoomInfoRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *MerchantRoomInfoRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type MerchantRoomInfoResponse struct {
	Reverse              string   `protobuf:"bytes,1,opt,name=reverse" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantRoomInfoResponse) Reset()         { *m = MerchantRoomInfoResponse{} }
func (m *MerchantRoomInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantRoomInfoResponse) ProtoMessage()    {}
func (*MerchantRoomInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{6}
}
func (m *MerchantRoomInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantRoomInfoResponse.Unmarshal(m, b)
}
func (m *MerchantRoomInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantRoomInfoResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantRoomInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantRoomInfoResponse.Merge(dst, src)
}
func (m *MerchantRoomInfoResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantRoomInfoResponse.Size(m)
}
func (m *MerchantRoomInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantRoomInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantRoomInfoResponse proto.InternalMessageInfo

func (m *MerchantRoomInfoResponse) GetReverse() string {
	if m != nil {
		return m.Reverse
	}
	return ""
}

type MerchantOpenRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Cellphone            string   `protobuf:"bytes,2,opt,name=cellphone" json:"cellphone,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	PaymentBit           uint32   `protobuf:"varint,4,opt,name=paymentBit" json:"paymentBit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantOpenRequest) Reset()         { *m = MerchantOpenRequest{} }
func (m *MerchantOpenRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantOpenRequest) ProtoMessage()    {}
func (*MerchantOpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{7}
}
func (m *MerchantOpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantOpenRequest.Unmarshal(m, b)
}
func (m *MerchantOpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantOpenRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantOpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantOpenRequest.Merge(dst, src)
}
func (m *MerchantOpenRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantOpenRequest.Size(m)
}
func (m *MerchantOpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantOpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantOpenRequest proto.InternalMessageInfo

func (m *MerchantOpenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantOpenRequest) GetCellphone() string {
	if m != nil {
		return m.Cellphone
	}
	return ""
}

func (m *MerchantOpenRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MerchantOpenRequest) GetPaymentBit() uint32 {
	if m != nil {
		return m.PaymentBit
	}
	return 0
}

type MerchantOpenResponse struct {
	Successed            bool     `protobuf:"varint,1,opt,name=successed" json:"successed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantOpenResponse) Reset()         { *m = MerchantOpenResponse{} }
func (m *MerchantOpenResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantOpenResponse) ProtoMessage()    {}
func (*MerchantOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{8}
}
func (m *MerchantOpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantOpenResponse.Unmarshal(m, b)
}
func (m *MerchantOpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantOpenResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantOpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantOpenResponse.Merge(dst, src)
}
func (m *MerchantOpenResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantOpenResponse.Size(m)
}
func (m *MerchantOpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantOpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantOpenResponse proto.InternalMessageInfo

func (m *MerchantOpenResponse) GetSuccessed() bool {
	if m != nil {
		return m.Successed
	}
	return false
}

type MerchantRegisterRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VerifyCode           string   `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Role                 uint32   `protobuf:"varint,5,opt,name=role" json:"role,omitempty"`
	MerchantID           uint32   `protobuf:"varint,6,opt,name=merchantID" json:"merchantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantRegisterRequest) Reset()         { *m = MerchantRegisterRequest{} }
func (m *MerchantRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantRegisterRequest) ProtoMessage()    {}
func (*MerchantRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{9}
}
func (m *MerchantRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantRegisterRequest.Unmarshal(m, b)
}
func (m *MerchantRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantRegisterRequest.Merge(dst, src)
}
func (m *MerchantRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantRegisterRequest.Size(m)
}
func (m *MerchantRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantRegisterRequest proto.InternalMessageInfo

func (m *MerchantRegisterRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MerchantRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantRegisterRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *MerchantRegisterRequest) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *MerchantRegisterRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

type MerchantRegisterResponse struct {
	Successed            bool     `protobuf:"varint,1,opt,name=successed" json:"successed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantRegisterResponse) Reset()         { *m = MerchantRegisterResponse{} }
func (m *MerchantRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantRegisterResponse) ProtoMessage()    {}
func (*MerchantRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{10}
}
func (m *MerchantRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantRegisterResponse.Unmarshal(m, b)
}
func (m *MerchantRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantRegisterResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantRegisterResponse.Merge(dst, src)
}
func (m *MerchantRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantRegisterResponse.Size(m)
}
func (m *MerchantRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantRegisterResponse proto.InternalMessageInfo

func (m *MerchantRegisterResponse) GetSuccessed() bool {
	if m != nil {
		return m.Successed
	}
	return false
}

type MerchantChangePswRequest struct {
	NewPsw               string   `protobuf:"bytes,1,opt,name=newPsw" json:"newPsw,omitempty"`
	SessionToken         string   `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	VerifyCode           string   `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Cellphone            string   `protobuf:"bytes,4,opt,name=cellphone" json:"cellphone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantChangePswRequest) Reset()         { *m = MerchantChangePswRequest{} }
func (m *MerchantChangePswRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantChangePswRequest) ProtoMessage()    {}
func (*MerchantChangePswRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{11}
}
func (m *MerchantChangePswRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantChangePswRequest.Unmarshal(m, b)
}
func (m *MerchantChangePswRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantChangePswRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantChangePswRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantChangePswRequest.Merge(dst, src)
}
func (m *MerchantChangePswRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantChangePswRequest.Size(m)
}
func (m *MerchantChangePswRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantChangePswRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantChangePswRequest proto.InternalMessageInfo

func (m *MerchantChangePswRequest) GetNewPsw() string {
	if m != nil {
		return m.NewPsw
	}
	return ""
}

func (m *MerchantChangePswRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *MerchantChangePswRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *MerchantChangePswRequest) GetCellphone() string {
	if m != nil {
		return m.Cellphone
	}
	return ""
}

type MerchantChangePswResponse struct {
	Successed            bool     `protobuf:"varint,1,opt,name=successed" json:"successed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantChangePswResponse) Reset()         { *m = MerchantChangePswResponse{} }
func (m *MerchantChangePswResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantChangePswResponse) ProtoMessage()    {}
func (*MerchantChangePswResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{12}
}
func (m *MerchantChangePswResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantChangePswResponse.Unmarshal(m, b)
}
func (m *MerchantChangePswResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantChangePswResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantChangePswResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantChangePswResponse.Merge(dst, src)
}
func (m *MerchantChangePswResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantChangePswResponse.Size(m)
}
func (m *MerchantChangePswResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantChangePswResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantChangePswResponse proto.InternalMessageInfo

func (m *MerchantChangePswResponse) GetSuccessed() bool {
	if m != nil {
		return m.Successed
	}
	return false
}

type MerchantLoginRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	TokenRequest         string   `protobuf:"bytes,2,opt,name=tokenRequest" json:"tokenRequest,omitempty"`
	MerchantID           uint32   `protobuf:"varint,3,opt,name=merchantID" json:"merchantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantLoginRequest) Reset()         { *m = MerchantLoginRequest{} }
func (m *MerchantLoginRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantLoginRequest) ProtoMessage()    {}
func (*MerchantLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{13}
}
func (m *MerchantLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantLoginRequest.Unmarshal(m, b)
}
func (m *MerchantLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantLoginRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantLoginRequest.Merge(dst, src)
}
func (m *MerchantLoginRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantLoginRequest.Size(m)
}
func (m *MerchantLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantLoginRequest proto.InternalMessageInfo

func (m *MerchantLoginRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MerchantLoginRequest) GetTokenRequest() string {
	if m != nil {
		return m.TokenRequest
	}
	return ""
}

func (m *MerchantLoginRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

type MerchantLoginResponse struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	Successed            bool     `protobuf:"varint,2,opt,name=successed" json:"successed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantLoginResponse) Reset()         { *m = MerchantLoginResponse{} }
func (m *MerchantLoginResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantLoginResponse) ProtoMessage()    {}
func (*MerchantLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{14}
}
func (m *MerchantLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantLoginResponse.Unmarshal(m, b)
}
func (m *MerchantLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantLoginResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantLoginResponse.Merge(dst, src)
}
func (m *MerchantLoginResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantLoginResponse.Size(m)
}
func (m *MerchantLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantLoginResponse proto.InternalMessageInfo

func (m *MerchantLoginResponse) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *MerchantLoginResponse) GetSuccessed() bool {
	if m != nil {
		return m.Successed
	}
	return false
}

type MerchantInfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MerchantID           string   `protobuf:"bytes,2,opt,name=merchantID" json:"merchantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantInfoRequest) Reset()         { *m = MerchantInfoRequest{} }
func (m *MerchantInfoRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantInfoRequest) ProtoMessage()    {}
func (*MerchantInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{15}
}
func (m *MerchantInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantInfoRequest.Unmarshal(m, b)
}
func (m *MerchantInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantInfoRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantInfoRequest.Merge(dst, src)
}
func (m *MerchantInfoRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantInfoRequest.Size(m)
}
func (m *MerchantInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantInfoRequest proto.InternalMessageInfo

func (m *MerchantInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MerchantInfoRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

type InnerMerchantAccount struct {
	Role                 uint32   `protobuf:"varint,1,opt,name=role" json:"role,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMerchantAccount) Reset()         { *m = InnerMerchantAccount{} }
func (m *InnerMerchantAccount) String() string { return proto.CompactTextString(m) }
func (*InnerMerchantAccount) ProtoMessage()    {}
func (*InnerMerchantAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{16}
}
func (m *InnerMerchantAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMerchantAccount.Unmarshal(m, b)
}
func (m *InnerMerchantAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMerchantAccount.Marshal(b, m, deterministic)
}
func (dst *InnerMerchantAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMerchantAccount.Merge(dst, src)
}
func (m *InnerMerchantAccount) XXX_Size() int {
	return xxx_messageInfo_InnerMerchantAccount.Size(m)
}
func (m *InnerMerchantAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMerchantAccount.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMerchantAccount proto.InternalMessageInfo

func (m *InnerMerchantAccount) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *InnerMerchantAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MerchantInfoResponse struct {
	MerchantName         string                `protobuf:"bytes,1,opt,name=merchantName" json:"merchantName,omitempty"`
	MerchantAccount      *InnerMerchantAccount `protobuf:"bytes,2,opt,name=merchantAccount" json:"merchantAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MerchantInfoResponse) Reset()         { *m = MerchantInfoResponse{} }
func (m *MerchantInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantInfoResponse) ProtoMessage()    {}
func (*MerchantInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_4a288b659b022119, []int{17}
}
func (m *MerchantInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantInfoResponse.Unmarshal(m, b)
}
func (m *MerchantInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantInfoResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantInfoResponse.Merge(dst, src)
}
func (m *MerchantInfoResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantInfoResponse.Size(m)
}
func (m *MerchantInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantInfoResponse proto.InternalMessageInfo

func (m *MerchantInfoResponse) GetMerchantName() string {
	if m != nil {
		return m.MerchantName
	}
	return ""
}

func (m *MerchantInfoResponse) GetMerchantAccount() *InnerMerchantAccount {
	if m != nil {
		return m.MerchantAccount
	}
	return nil
}

func init() {
	proto.RegisterType((*MerchantWaiterInfor)(nil), "Aphro.Merchant.pb.MerchantWaiterInfor")
	proto.RegisterType((*MerchantWaiterCreateRequest)(nil), "Aphro.Merchant.pb.MerchantWaiterCreateRequest")
	proto.RegisterType((*MerchantWaiterCreateRespone)(nil), "Aphro.Merchant.pb.MerchantWaiterCreateRespone")
	proto.RegisterType((*MerchantWaiterDeleteRequest)(nil), "Aphro.Merchant.pb.MerchantWaiterDeleteRequest")
	proto.RegisterType((*MerchantWaiterDeleteRespone)(nil), "Aphro.Merchant.pb.MerchantWaiterDeleteRespone")
	proto.RegisterType((*MerchantRoomInfoRequest)(nil), "Aphro.Merchant.pb.MerchantRoomInfoRequest")
	proto.RegisterType((*MerchantRoomInfoResponse)(nil), "Aphro.Merchant.pb.MerchantRoomInfoResponse")
	proto.RegisterType((*MerchantOpenRequest)(nil), "Aphro.Merchant.pb.MerchantOpenRequest")
	proto.RegisterType((*MerchantOpenResponse)(nil), "Aphro.Merchant.pb.MerchantOpenResponse")
	proto.RegisterType((*MerchantRegisterRequest)(nil), "Aphro.Merchant.pb.MerchantRegisterRequest")
	proto.RegisterType((*MerchantRegisterResponse)(nil), "Aphro.Merchant.pb.MerchantRegisterResponse")
	proto.RegisterType((*MerchantChangePswRequest)(nil), "Aphro.Merchant.pb.MerchantChangePswRequest")
	proto.RegisterType((*MerchantChangePswResponse)(nil), "Aphro.Merchant.pb.MerchantChangePswResponse")
	proto.RegisterType((*MerchantLoginRequest)(nil), "Aphro.Merchant.pb.MerchantLoginRequest")
	proto.RegisterType((*MerchantLoginResponse)(nil), "Aphro.Merchant.pb.MerchantLoginResponse")
	proto.RegisterType((*MerchantInfoRequest)(nil), "Aphro.Merchant.pb.MerchantInfoRequest")
	proto.RegisterType((*InnerMerchantAccount)(nil), "Aphro.Merchant.pb.InnerMerchantAccount")
	proto.RegisterType((*MerchantInfoResponse)(nil), "Aphro.Merchant.pb.MerchantInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MerchantService service

type MerchantServiceClient interface {
	// 商户开户
	MerchantOpen(ctx context.Context, in *MerchantOpenRequest, opts ...grpc.CallOption) (*MerchantOpenResponse, error)
	// 商户用户注册
	MerchantRegister(ctx context.Context, in *MerchantRegisterRequest, opts ...grpc.CallOption) (*MerchantRegisterResponse, error)
	// 商户用户修改密码
	MerchantChangePsw(ctx context.Context, in *MerchantChangePswRequest, opts ...grpc.CallOption) (*MerchantChangePswResponse, error)
	// 商户app登陆
	MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error)
	// 商户app 信息
	MerchantInfo(ctx context.Context, in *MerchantInfoRequest, opts ...grpc.CallOption) (*MerchantInfoResponse, error)
	// 商户app 信息
	MerchantRoomInfo(ctx context.Context, in *MerchantRoomInfoRequest, opts ...grpc.CallOption) (*MerchantRoomInfoResponse, error)
	// 新增商户服务信息
	MerchantWaiterCreate(ctx context.Context, in *MerchantWaiterCreateRequest, opts ...grpc.CallOption) (*MerchantWaiterCreateRespone, error)
	// 删除商户服务信息
	MerchantWaiterDelete(ctx context.Context, in *MerchantWaiterDeleteRequest, opts ...grpc.CallOption) (*MerchantWaiterDeleteRespone, error)
}

type merchantServiceClient struct {
	cc *grpc.ClientConn
}

func NewMerchantServiceClient(cc *grpc.ClientConn) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) MerchantOpen(ctx context.Context, in *MerchantOpenRequest, opts ...grpc.CallOption) (*MerchantOpenResponse, error) {
	out := new(MerchantOpenResponse)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantOpen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantRegister(ctx context.Context, in *MerchantRegisterRequest, opts ...grpc.CallOption) (*MerchantRegisterResponse, error) {
	out := new(MerchantRegisterResponse)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantChangePsw(ctx context.Context, in *MerchantChangePswRequest, opts ...grpc.CallOption) (*MerchantChangePswResponse, error) {
	out := new(MerchantChangePswResponse)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantChangePsw", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error) {
	out := new(MerchantLoginResponse)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantInfo(ctx context.Context, in *MerchantInfoRequest, opts ...grpc.CallOption) (*MerchantInfoResponse, error) {
	out := new(MerchantInfoResponse)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantRoomInfo(ctx context.Context, in *MerchantRoomInfoRequest, opts ...grpc.CallOption) (*MerchantRoomInfoResponse, error) {
	out := new(MerchantRoomInfoResponse)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantRoomInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantWaiterCreate(ctx context.Context, in *MerchantWaiterCreateRequest, opts ...grpc.CallOption) (*MerchantWaiterCreateRespone, error) {
	out := new(MerchantWaiterCreateRespone)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantWaiterCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantWaiterDelete(ctx context.Context, in *MerchantWaiterDeleteRequest, opts ...grpc.CallOption) (*MerchantWaiterDeleteRespone, error) {
	out := new(MerchantWaiterDeleteRespone)
	err := grpc.Invoke(ctx, "/Aphro.Merchant.pb.MerchantService/merchantWaiterDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MerchantService service

type MerchantServiceServer interface {
	// 商户开户
	MerchantOpen(context.Context, *MerchantOpenRequest) (*MerchantOpenResponse, error)
	// 商户用户注册
	MerchantRegister(context.Context, *MerchantRegisterRequest) (*MerchantRegisterResponse, error)
	// 商户用户修改密码
	MerchantChangePsw(context.Context, *MerchantChangePswRequest) (*MerchantChangePswResponse, error)
	// 商户app登陆
	MerchantLogin(context.Context, *MerchantLoginRequest) (*MerchantLoginResponse, error)
	// 商户app 信息
	MerchantInfo(context.Context, *MerchantInfoRequest) (*MerchantInfoResponse, error)
	// 商户app 信息
	MerchantRoomInfo(context.Context, *MerchantRoomInfoRequest) (*MerchantRoomInfoResponse, error)
	// 新增商户服务信息
	MerchantWaiterCreate(context.Context, *MerchantWaiterCreateRequest) (*MerchantWaiterCreateRespone, error)
	// 删除商户服务信息
	MerchantWaiterDelete(context.Context, *MerchantWaiterDeleteRequest) (*MerchantWaiterDeleteRespone, error)
}

func RegisterMerchantServiceServer(s *grpc.Server, srv MerchantServiceServer) {
	s.RegisterService(&_MerchantService_serviceDesc, srv)
}

func _MerchantService_MerchantOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantOpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantOpen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantOpen(ctx, req.(*MerchantOpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantRegister(ctx, req.(*MerchantRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantChangePsw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantChangePswRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantChangePsw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantChangePsw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantChangePsw(ctx, req.(*MerchantChangePswRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantLogin(ctx, req.(*MerchantLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantInfo(ctx, req.(*MerchantInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantRoomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantRoomInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantRoomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantRoomInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantRoomInfo(ctx, req.(*MerchantRoomInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantWaiterCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantWaiterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantWaiterCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantWaiterCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantWaiterCreate(ctx, req.(*MerchantWaiterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantWaiterDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantWaiterDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantWaiterDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Merchant.pb.MerchantService/MerchantWaiterDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantWaiterDelete(ctx, req.(*MerchantWaiterDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Aphro.Merchant.pb.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "merchantOpen",
			Handler:    _MerchantService_MerchantOpen_Handler,
		},
		{
			MethodName: "merchantRegister",
			Handler:    _MerchantService_MerchantRegister_Handler,
		},
		{
			MethodName: "merchantChangePsw",
			Handler:    _MerchantService_MerchantChangePsw_Handler,
		},
		{
			MethodName: "merchantLogin",
			Handler:    _MerchantService_MerchantLogin_Handler,
		},
		{
			MethodName: "merchantInfo",
			Handler:    _MerchantService_MerchantInfo_Handler,
		},
		{
			MethodName: "merchantRoomInfo",
			Handler:    _MerchantService_MerchantRoomInfo_Handler,
		},
		{
			MethodName: "merchantWaiterCreate",
			Handler:    _MerchantService_MerchantWaiterCreate_Handler,
		},
		{
			MethodName: "merchantWaiterDelete",
			Handler:    _MerchantService_MerchantWaiterDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}

func init() { proto.RegisterFile("merchant.proto", fileDescriptor_merchant_4a288b659b022119) }

var fileDescriptor_merchant_4a288b659b022119 = []byte{
	// 866 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdf, 0x6f, 0xdc, 0x44,
	0x10, 0xc7, 0xb5, 0x97, 0xf4, 0xc8, 0x4d, 0xd3, 0xa6, 0xdd, 0x1c, 0x8d, 0x63, 0x42, 0x88, 0xf6,
	0x81, 0x46, 0x01, 0xdd, 0x49, 0xa1, 0x0f, 0x50, 0xa4, 0x4a, 0x25, 0x7d, 0x89, 0xf8, 0x55, 0x0c,
	0x08, 0xf1, 0xe8, 0xfa, 0x26, 0x17, 0xab, 0xe7, 0x5d, 0xb3, 0xeb, 0xe4, 0x14, 0x10, 0x48, 0xf0,
	0x88, 0x80, 0x97, 0xf0, 0xc4, 0xbf, 0xc5, 0xbf, 0xc0, 0x1f, 0xc0, 0x9f, 0x80, 0xbc, 0xde, 0x3d,
	0xaf, 0x7d, 0x8e, 0xcf, 0xa2, 0x6f, 0xde, 0xd1, 0xec, 0xce, 0x67, 0x66, 0xbf, 0xe3, 0x1d, 0xb8,
	0x9b, 0xa0, 0x8c, 0xce, 0x43, 0x9e, 0x8d, 0x52, 0x29, 0x32, 0x41, 0xef, 0x3f, 0x4d, 0xcf, 0xa5,
	0x18, 0x7d, 0xba, 0xb0, 0xbe, 0xf0, 0xf7, 0xa6, 0x42, 0x4c, 0x67, 0x38, 0x0e, 0xd3, 0x78, 0x1c,
	0x72, 0x2e, 0xb2, 0x30, 0x8b, 0x05, 0x57, 0xc5, 0x06, 0x76, 0x02, 0xdb, 0xd6, 0xf9, 0x9b, 0x30,
	0xce, 0x50, 0x9e, 0xf2, 0x33, 0x21, 0x29, 0x85, 0x75, 0x1e, 0x26, 0xe8, 0x91, 0x03, 0x72, 0x38,
	0x08, 0xf4, 0x37, 0xf5, 0xe0, 0xb5, 0x38, 0x09, 0xa7, 0x78, 0xfa, 0xcc, 0xeb, 0x1d, 0x90, 0x43,
	0x12, 0xd8, 0x25, 0xbb, 0x26, 0xf0, 0x46, 0xf5, 0x94, 0x13, 0x89, 0x61, 0x86, 0x01, 0x7e, 0x77,
	0x81, 0x2a, 0xa3, 0x43, 0xb8, 0x95, 0x89, 0x97, 0xc8, 0xcd, 0x71, 0xc5, 0x82, 0xee, 0x03, 0x58,
	0x7a, 0x73, 0xe4, 0x20, 0x70, 0x2c, 0xf4, 0x09, 0xf4, 0xe7, 0xfa, 0x30, 0x6f, 0xed, 0x80, 0x1c,
	0xde, 0x3e, 0x7e, 0x7b, 0xb4, 0x94, 0xdc, 0xa8, 0x81, 0x3d, 0x30, 0xbb, 0xd8, 0x87, 0x37, 0x41,
	0xa9, 0x54, 0x70, 0xa4, 0x7b, 0x30, 0x50, 0x17, 0x51, 0x84, 0x4a, 0xe1, 0x44, 0x83, 0x6d, 0x04,
	0xa5, 0x81, 0x89, 0xfa, 0xe6, 0x67, 0x38, 0xc3, 0x57, 0xcd, 0xc8, 0x87, 0x8d, 0x82, 0x2d, 0x9e,
	0xe8, 0x9c, 0xd6, 0x83, 0xc5, 0x7a, 0x99, 0xd6, 0x06, 0xec, 0x42, 0xfb, 0x35, 0xec, 0xd8, 0xcd,
	0x81, 0x10, 0x49, 0x5e, 0x07, 0x4b, 0xca, 0x60, 0x53, 0xa1, 0x52, 0xb1, 0xe0, 0x5f, 0x39, 0xc0,
	0x15, 0x1b, 0x7d, 0x00, 0x7d, 0x99, 0x6f, 0x2b, 0x98, 0xef, 0x04, 0x66, 0xc5, 0x1e, 0x81, 0xb7,
	0x7c, 0x6c, 0xce, 0xa3, 0xb4, 0x1a, 0x24, 0x5e, 0xa2, 0x54, 0x56, 0x24, 0x76, 0xc9, 0x7e, 0x26,
	0xa5, 0xa6, 0x3e, 0x4f, 0x91, 0x5b, 0x92, 0x26, 0x4d, 0xed, 0xc1, 0x20, 0xc2, 0xd9, 0x2c, 0x3d,
	0x17, 0x1c, 0x4d, 0xc1, 0x4a, 0x43, 0x1e, 0x23, 0x9c, 0x4c, 0x24, 0x2a, 0xa5, 0xcb, 0x35, 0x08,
	0xec, 0x32, 0xaf, 0x74, 0x1a, 0x5e, 0x25, 0xc8, 0xb3, 0x8f, 0xe2, 0xcc, 0x5b, 0xd7, 0xd4, 0x8e,
	0x85, 0x3d, 0x82, 0x61, 0x15, 0xc1, 0x50, 0xb7, 0x97, 0xf1, 0x9a, 0x38, 0x75, 0xc4, 0x69, 0xac,
	0x32, 0x94, 0x96, 0xfe, 0x1e, 0xac, 0xbd, 0xc4, 0x2b, 0x03, 0x9f, 0x7f, 0x2e, 0xf2, 0xe9, 0x39,
	0xf9, 0xec, 0x03, 0x5c, 0xa2, 0x8c, 0xcf, 0xae, 0x4e, 0xc4, 0x04, 0x0d, 0xb4, 0x63, 0xc9, 0xf7,
	0x48, 0x31, 0x43, 0xef, 0x96, 0x26, 0xd6, 0xdf, 0x35, 0xd5, 0xf4, 0x8b, 0x5c, 0x4a, 0x0b, 0x7b,
	0xdf, 0xb9, 0x85, 0x05, 0x54, 0xa7, 0x7c, 0xfe, 0x24, 0xe5, 0xd6, 0x93, 0xf3, 0x90, 0x4f, 0xf1,
	0xb9, 0x9a, 0xdb, 0x84, 0x1e, 0x40, 0x9f, 0xe3, 0xfc, 0xb9, 0x9a, 0x9b, 0x9c, 0xcc, 0x6a, 0x49,
	0x30, 0xbd, 0x06, 0xc1, 0xac, 0x4a, 0xb3, 0x72, 0xad, 0xeb, 0xb5, 0x6b, 0x65, 0x1f, 0xc0, 0x6e,
	0x03, 0x55, 0xa7, 0x8c, 0x66, 0xe5, 0xbd, 0x7e, 0x22, 0xa6, 0x31, 0xbf, 0xf9, 0x76, 0x18, 0x6c,
	0xea, 0xa6, 0x34, 0x1e, 0x36, 0x0d, 0xd7, 0x56, 0xab, 0xfc, 0xda, 0x52, 0xe5, 0xbf, 0x85, 0xd7,
	0x6b, 0xd1, 0x0c, 0x64, 0x97, 0xa6, 0xaa, 0x24, 0xd2, 0xab, 0x27, 0xf2, 0x71, 0xd9, 0x23, 0x6e,
	0xb7, 0xfe, 0xaf, 0xff, 0x0a, 0x7b, 0x02, 0xc3, 0x53, 0xce, 0x51, 0xda, 0x13, 0x9f, 0x46, 0x91,
	0xb8, 0xe0, 0xd9, 0x42, 0x6d, 0xc4, 0x51, 0x5b, 0x83, 0x6a, 0xd9, 0xef, 0xa4, 0x2c, 0x6b, 0xa5,
	0xc9, 0x19, 0x6c, 0xda, 0x30, 0x9f, 0x95, 0xad, 0x5b, 0xb1, 0xd1, 0x2f, 0x60, 0x2b, 0xa9, 0xc6,
	0xd5, 0x67, 0xdf, 0x3e, 0x7e, 0xd8, 0xf0, 0xbf, 0x6e, 0xc2, 0x0c, 0xea, 0xfb, 0x8f, 0xff, 0xdd,
	0x80, 0x2d, 0xeb, 0xf4, 0x25, 0xca, 0xcb, 0x38, 0x42, 0xfa, 0x7d, 0x89, 0x92, 0x77, 0x34, 0x6d,
	0x7b, 0x0d, 0x9c, 0xbf, 0x8e, 0xff, 0x70, 0xa5, 0x5f, 0x91, 0x2b, 0xdb, 0xfd, 0xe5, 0xef, 0x7f,
	0xae, 0x7b, 0xdb, 0xec, 0xee, 0xd8, 0xc6, 0x19, 0x8b, 0x14, 0xf9, 0x63, 0x72, 0x44, 0x7f, 0x25,
	0x70, 0x2f, 0xa9, 0xb5, 0x20, 0x3d, 0x6a, 0x39, 0xb8, 0xf6, 0xf3, 0xf0, 0xdf, 0xe9, 0xe4, 0x6b,
	0x40, 0xde, 0xd4, 0x20, 0x3b, 0x8c, 0x96, 0x20, 0xd2, 0xf8, 0xe4, 0x30, 0x7f, 0x10, 0xb8, 0x9f,
	0xd4, 0xdb, 0x87, 0xb6, 0x45, 0xa8, 0xb7, 0xbe, 0xff, 0x6e, 0x37, 0x67, 0xc3, 0xb3, 0xaf, 0x79,
	0x3c, 0xb6, 0x5d, 0xf2, 0x44, 0xd6, 0x29, 0x07, 0xfa, 0x09, 0xee, 0x24, 0x6e, 0x97, 0xd0, 0xb6,
	0x92, 0xbb, 0x5d, 0xeb, 0x1f, 0xae, 0x76, 0x34, 0x0c, 0xbe, 0x66, 0x18, 0xb2, 0xad, 0x92, 0x61,
	0x96, 0x3b, 0xe4, 0xf1, 0x1d, 0x65, 0xe4, 0xe2, 0x6d, 0x55, 0x86, 0xd3, 0x6b, 0xad, 0xca, 0x70,
	0xbb, 0xa0, 0x49, 0x19, 0x31, 0x3f, 0x13, 0x79, 0xec, 0xdf, 0x5c, 0x65, 0x98, 0x27, 0xb2, 0x5d,
	0x19, 0xd5, 0xe7, 0xb9, 0x5d, 0x19, 0xb5, 0x37, 0x97, 0xbd, 0xa5, 0x41, 0x76, 0xe9, 0x8e, 0xa3,
	0x0c, 0x21, 0x92, 0xf1, 0x0f, 0xc5, 0x7b, 0xfd, 0x23, 0xfd, 0x8b, 0xc0, 0x30, 0x69, 0x98, 0x79,
	0xe8, 0x68, 0xe5, 0xec, 0x54, 0x99, 0xd8, 0xfc, 0xee, 0xfe, 0x7a, 0x3c, 0x61, 0x4c, 0x93, 0xed,
	0x31, 0x87, 0xac, 0x98, 0x6c, 0xc6, 0x91, 0xf6, 0xcb, 0x6b, 0xb5, 0x0c, 0x57, 0x8c, 0x38, 0x1d,
	0xe0, 0x2a, 0xc3, 0x97, 0xdf, 0xdd, 0x7f, 0x15, 0xdc, 0x44, 0xfb, 0x3d, 0x26, 0x47, 0x2f, 0xfa,
	0x7a, 0x1c, 0x7e, 0xef, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xc7, 0x45, 0xe8, 0x51, 0x0b,
	0x00, 0x00,
}
