// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encryption.proto

/*
Package EncryptionService_Pb is a generated protocol buffer package.

It is generated from these files:
	encryption.proto

It has these top-level messages:
	EncryptionBase64DecodeRequest
	EncryptionBase64DecodeResponse
	EncryptionBase64EncodeRequest
	EncryptionBase64EncodeResponse
	EncryptionXXTEARequest
	EncryptionXXTEAResponse
	DecryptionXXTEARequest
	DecryptionXXTEAResponse
	EncryptionRSARequest
	EncryptionRSAResponse
	DecryptionRSARequest
	DecryptionRSAResponse
*/
package EncryptionService_Pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptionBase64DecodeRequest struct {
	DecodedStr []byte `protobuf:"bytes,1,opt,name=decodedStr,proto3" json:"decodedStr,omitempty"`
}

func (m *EncryptionBase64DecodeRequest) Reset()                    { *m = EncryptionBase64DecodeRequest{} }
func (m *EncryptionBase64DecodeRequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptionBase64DecodeRequest) ProtoMessage()               {}
func (*EncryptionBase64DecodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EncryptionBase64DecodeRequest) GetDecodedStr() []byte {
	if m != nil {
		return m.DecodedStr
	}
	return nil
}

type EncryptionBase64DecodeResponse struct {
	RawValue string `protobuf:"bytes,1,opt,name=rawValue" json:"rawValue,omitempty"`
}

func (m *EncryptionBase64DecodeResponse) Reset()                    { *m = EncryptionBase64DecodeResponse{} }
func (m *EncryptionBase64DecodeResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptionBase64DecodeResponse) ProtoMessage()               {}
func (*EncryptionBase64DecodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EncryptionBase64DecodeResponse) GetRawValue() string {
	if m != nil {
		return m.RawValue
	}
	return ""
}

type EncryptionBase64EncodeRequest struct {
	RawValue string `protobuf:"bytes,1,opt,name=rawValue" json:"rawValue,omitempty"`
}

func (m *EncryptionBase64EncodeRequest) Reset()                    { *m = EncryptionBase64EncodeRequest{} }
func (m *EncryptionBase64EncodeRequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptionBase64EncodeRequest) ProtoMessage()               {}
func (*EncryptionBase64EncodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EncryptionBase64EncodeRequest) GetRawValue() string {
	if m != nil {
		return m.RawValue
	}
	return ""
}

type EncryptionBase64EncodeResponse struct {
	EncodedStr []byte `protobuf:"bytes,1,opt,name=encodedStr,proto3" json:"encodedStr,omitempty"`
}

func (m *EncryptionBase64EncodeResponse) Reset()                    { *m = EncryptionBase64EncodeResponse{} }
func (m *EncryptionBase64EncodeResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptionBase64EncodeResponse) ProtoMessage()               {}
func (*EncryptionBase64EncodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EncryptionBase64EncodeResponse) GetEncodedStr() []byte {
	if m != nil {
		return m.EncodedStr
	}
	return nil
}

// /////////////// XXTEA /////////////////////
type EncryptionXXTEARequest struct {
	Key      string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	RawValue string `protobuf:"bytes,2,opt,name=rawValue" json:"rawValue,omitempty"`
}

func (m *EncryptionXXTEARequest) Reset()                    { *m = EncryptionXXTEARequest{} }
func (m *EncryptionXXTEARequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptionXXTEARequest) ProtoMessage()               {}
func (*EncryptionXXTEARequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EncryptionXXTEARequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EncryptionXXTEARequest) GetRawValue() string {
	if m != nil {
		return m.RawValue
	}
	return ""
}

type EncryptionXXTEAResponse struct {
	Key          string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	EncryptedStr []byte `protobuf:"bytes,2,opt,name=encryptedStr,proto3" json:"encryptedStr,omitempty"`
}

func (m *EncryptionXXTEAResponse) Reset()                    { *m = EncryptionXXTEAResponse{} }
func (m *EncryptionXXTEAResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptionXXTEAResponse) ProtoMessage()               {}
func (*EncryptionXXTEAResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EncryptionXXTEAResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EncryptionXXTEAResponse) GetEncryptedStr() []byte {
	if m != nil {
		return m.EncryptedStr
	}
	return nil
}

type DecryptionXXTEARequest struct {
	Key          string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	EncryptedStr []byte `protobuf:"bytes,2,opt,name=encryptedStr,proto3" json:"encryptedStr,omitempty"`
}

func (m *DecryptionXXTEARequest) Reset()                    { *m = DecryptionXXTEARequest{} }
func (m *DecryptionXXTEARequest) String() string            { return proto.CompactTextString(m) }
func (*DecryptionXXTEARequest) ProtoMessage()               {}
func (*DecryptionXXTEARequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DecryptionXXTEARequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DecryptionXXTEARequest) GetEncryptedStr() []byte {
	if m != nil {
		return m.EncryptedStr
	}
	return nil
}

type DecryptionXXTEAResponse struct {
	Key      string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	RawValue string `protobuf:"bytes,2,opt,name=rawValue" json:"rawValue,omitempty"`
}

func (m *DecryptionXXTEAResponse) Reset()                    { *m = DecryptionXXTEAResponse{} }
func (m *DecryptionXXTEAResponse) String() string            { return proto.CompactTextString(m) }
func (*DecryptionXXTEAResponse) ProtoMessage()               {}
func (*DecryptionXXTEAResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DecryptionXXTEAResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DecryptionXXTEAResponse) GetRawValue() string {
	if m != nil {
		return m.RawValue
	}
	return ""
}

// //////////////RSA //////////////////////
type EncryptionRSARequest struct {
	RawValue string `protobuf:"bytes,2,opt,name=rawValue" json:"rawValue,omitempty"`
}

func (m *EncryptionRSARequest) Reset()                    { *m = EncryptionRSARequest{} }
func (m *EncryptionRSARequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptionRSARequest) ProtoMessage()               {}
func (*EncryptionRSARequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EncryptionRSARequest) GetRawValue() string {
	if m != nil {
		return m.RawValue
	}
	return ""
}

type EncryptionRSAResponse struct {
	EncryptedStr []byte `protobuf:"bytes,1,opt,name=encryptedStr,proto3" json:"encryptedStr,omitempty"`
}

func (m *EncryptionRSAResponse) Reset()                    { *m = EncryptionRSAResponse{} }
func (m *EncryptionRSAResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptionRSAResponse) ProtoMessage()               {}
func (*EncryptionRSAResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EncryptionRSAResponse) GetEncryptedStr() []byte {
	if m != nil {
		return m.EncryptedStr
	}
	return nil
}

type DecryptionRSARequest struct {
	EncryptedStr []byte `protobuf:"bytes,2,opt,name=encryptedStr,proto3" json:"encryptedStr,omitempty"`
}

func (m *DecryptionRSARequest) Reset()                    { *m = DecryptionRSARequest{} }
func (m *DecryptionRSARequest) String() string            { return proto.CompactTextString(m) }
func (*DecryptionRSARequest) ProtoMessage()               {}
func (*DecryptionRSARequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DecryptionRSARequest) GetEncryptedStr() []byte {
	if m != nil {
		return m.EncryptedStr
	}
	return nil
}

type DecryptionRSAResponse struct {
	RawValue string `protobuf:"bytes,2,opt,name=rawValue" json:"rawValue,omitempty"`
}

func (m *DecryptionRSAResponse) Reset()                    { *m = DecryptionRSAResponse{} }
func (m *DecryptionRSAResponse) String() string            { return proto.CompactTextString(m) }
func (*DecryptionRSAResponse) ProtoMessage()               {}
func (*DecryptionRSAResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DecryptionRSAResponse) GetRawValue() string {
	if m != nil {
		return m.RawValue
	}
	return ""
}

func init() {
	proto.RegisterType((*EncryptionBase64DecodeRequest)(nil), "EncryptionService.Pb.EncryptionBase64DecodeRequest")
	proto.RegisterType((*EncryptionBase64DecodeResponse)(nil), "EncryptionService.Pb.EncryptionBase64DecodeResponse")
	proto.RegisterType((*EncryptionBase64EncodeRequest)(nil), "EncryptionService.Pb.EncryptionBase64EncodeRequest")
	proto.RegisterType((*EncryptionBase64EncodeResponse)(nil), "EncryptionService.Pb.EncryptionBase64EncodeResponse")
	proto.RegisterType((*EncryptionXXTEARequest)(nil), "EncryptionService.Pb.EncryptionXXTEARequest")
	proto.RegisterType((*EncryptionXXTEAResponse)(nil), "EncryptionService.Pb.EncryptionXXTEAResponse")
	proto.RegisterType((*DecryptionXXTEARequest)(nil), "EncryptionService.Pb.DecryptionXXTEARequest")
	proto.RegisterType((*DecryptionXXTEAResponse)(nil), "EncryptionService.Pb.DecryptionXXTEAResponse")
	proto.RegisterType((*EncryptionRSARequest)(nil), "EncryptionService.Pb.EncryptionRSARequest")
	proto.RegisterType((*EncryptionRSAResponse)(nil), "EncryptionService.Pb.EncryptionRSAResponse")
	proto.RegisterType((*DecryptionRSARequest)(nil), "EncryptionService.Pb.DecryptionRSARequest")
	proto.RegisterType((*DecryptionRSAResponse)(nil), "EncryptionService.Pb.DecryptionRSAResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EncryptionService service

type EncryptionServiceClient interface {
	Base64Encode(ctx context.Context, in *EncryptionBase64EncodeRequest, opts ...grpc.CallOption) (*EncryptionBase64EncodeResponse, error)
	Base64Decode(ctx context.Context, in *EncryptionBase64DecodeRequest, opts ...grpc.CallOption) (*EncryptionBase64DecodeResponse, error)
	XxteaEncryption(ctx context.Context, in *EncryptionXXTEARequest, opts ...grpc.CallOption) (*EncryptionXXTEAResponse, error)
	XxteaDecryption(ctx context.Context, in *DecryptionXXTEARequest, opts ...grpc.CallOption) (*DecryptionXXTEAResponse, error)
	RsaEncryption(ctx context.Context, in *EncryptionRSARequest, opts ...grpc.CallOption) (*EncryptionRSAResponse, error)
	RsaDecryption(ctx context.Context, in *DecryptionRSARequest, opts ...grpc.CallOption) (*DecryptionRSAResponse, error)
}

type encryptionServiceClient struct {
	cc *grpc.ClientConn
}

func NewEncryptionServiceClient(cc *grpc.ClientConn) EncryptionServiceClient {
	return &encryptionServiceClient{cc}
}

func (c *encryptionServiceClient) Base64Encode(ctx context.Context, in *EncryptionBase64EncodeRequest, opts ...grpc.CallOption) (*EncryptionBase64EncodeResponse, error) {
	out := new(EncryptionBase64EncodeResponse)
	err := grpc.Invoke(ctx, "/EncryptionService.Pb.EncryptionService/base64Encode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionServiceClient) Base64Decode(ctx context.Context, in *EncryptionBase64DecodeRequest, opts ...grpc.CallOption) (*EncryptionBase64DecodeResponse, error) {
	out := new(EncryptionBase64DecodeResponse)
	err := grpc.Invoke(ctx, "/EncryptionService.Pb.EncryptionService/base64Decode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionServiceClient) XxteaEncryption(ctx context.Context, in *EncryptionXXTEARequest, opts ...grpc.CallOption) (*EncryptionXXTEAResponse, error) {
	out := new(EncryptionXXTEAResponse)
	err := grpc.Invoke(ctx, "/EncryptionService.Pb.EncryptionService/xxteaEncryption", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionServiceClient) XxteaDecryption(ctx context.Context, in *DecryptionXXTEARequest, opts ...grpc.CallOption) (*DecryptionXXTEAResponse, error) {
	out := new(DecryptionXXTEAResponse)
	err := grpc.Invoke(ctx, "/EncryptionService.Pb.EncryptionService/xxteaDecryption", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionServiceClient) RsaEncryption(ctx context.Context, in *EncryptionRSARequest, opts ...grpc.CallOption) (*EncryptionRSAResponse, error) {
	out := new(EncryptionRSAResponse)
	err := grpc.Invoke(ctx, "/EncryptionService.Pb.EncryptionService/rsaEncryption", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionServiceClient) RsaDecryption(ctx context.Context, in *DecryptionRSARequest, opts ...grpc.CallOption) (*DecryptionRSAResponse, error) {
	out := new(DecryptionRSAResponse)
	err := grpc.Invoke(ctx, "/EncryptionService.Pb.EncryptionService/rsaDecryption", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EncryptionService service

type EncryptionServiceServer interface {
	Base64Encode(context.Context, *EncryptionBase64EncodeRequest) (*EncryptionBase64EncodeResponse, error)
	Base64Decode(context.Context, *EncryptionBase64DecodeRequest) (*EncryptionBase64DecodeResponse, error)
	XxteaEncryption(context.Context, *EncryptionXXTEARequest) (*EncryptionXXTEAResponse, error)
	XxteaDecryption(context.Context, *DecryptionXXTEARequest) (*DecryptionXXTEAResponse, error)
	RsaEncryption(context.Context, *EncryptionRSARequest) (*EncryptionRSAResponse, error)
	RsaDecryption(context.Context, *DecryptionRSARequest) (*DecryptionRSAResponse, error)
}

func RegisterEncryptionServiceServer(s *grpc.Server, srv EncryptionServiceServer) {
	s.RegisterService(&_EncryptionService_serviceDesc, srv)
}

func _EncryptionService_Base64Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptionBase64EncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).Base64Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EncryptionService.Pb.EncryptionService/Base64Encode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).Base64Encode(ctx, req.(*EncryptionBase64EncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionService_Base64Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptionBase64DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).Base64Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EncryptionService.Pb.EncryptionService/Base64Decode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).Base64Decode(ctx, req.(*EncryptionBase64DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionService_XxteaEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptionXXTEARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).XxteaEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EncryptionService.Pb.EncryptionService/XxteaEncryption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).XxteaEncryption(ctx, req.(*EncryptionXXTEARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionService_XxteaDecryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptionXXTEARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).XxteaDecryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EncryptionService.Pb.EncryptionService/XxteaDecryption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).XxteaDecryption(ctx, req.(*DecryptionXXTEARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionService_RsaEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptionRSARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).RsaEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EncryptionService.Pb.EncryptionService/RsaEncryption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).RsaEncryption(ctx, req.(*EncryptionRSARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionService_RsaDecryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptionRSARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).RsaDecryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EncryptionService.Pb.EncryptionService/RsaDecryption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).RsaDecryption(ctx, req.(*DecryptionRSARequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EncryptionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EncryptionService.Pb.EncryptionService",
	HandlerType: (*EncryptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "base64Encode",
			Handler:    _EncryptionService_Base64Encode_Handler,
		},
		{
			MethodName: "base64Decode",
			Handler:    _EncryptionService_Base64Decode_Handler,
		},
		{
			MethodName: "xxteaEncryption",
			Handler:    _EncryptionService_XxteaEncryption_Handler,
		},
		{
			MethodName: "xxteaDecryption",
			Handler:    _EncryptionService_XxteaDecryption_Handler,
		},
		{
			MethodName: "rsaEncryption",
			Handler:    _EncryptionService_RsaEncryption_Handler,
		},
		{
			MethodName: "rsaDecryption",
			Handler:    _EncryptionService_RsaDecryption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryption.proto",
}

func init() { proto.RegisterFile("encryption.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcf, 0x8e, 0xd2, 0x50,
	0x14, 0xc6, 0xd3, 0x9a, 0xf8, 0xe7, 0x04, 0x33, 0x33, 0x0d, 0xc3, 0x4c, 0x1a, 0x20, 0xe6, 0xba,
	0x31, 0xa8, 0x6d, 0x02, 0xc4, 0x05, 0x9a, 0x28, 0x06, 0x74, 0xa7, 0xa6, 0x18, 0xc3, 0xb6, 0xd0,
	0x13, 0x42, 0x24, 0xbd, 0xb5, 0x2d, 0x0a, 0x4b, 0x8d, 0x4b, 0x77, 0xee, 0x7d, 0x29, 0x5f, 0xc1,
	0x07, 0x31, 0xb4, 0x85, 0x7b, 0xda, 0xdb, 0x7f, 0xb3, 0x83, 0x93, 0xfb, 0x9d, 0xef, 0x77, 0xcf,
	0x3d, 0x5f, 0x0a, 0xe7, 0xe8, 0x2e, 0xfd, 0xbd, 0x17, 0xae, 0xb9, 0x6b, 0x78, 0x3e, 0x0f, 0xb9,
	0xd6, 0x9c, 0x9e, 0x2a, 0x33, 0xf4, 0xbf, 0xae, 0x97, 0x68, 0x7c, 0x58, 0xe8, 0xed, 0x15, 0xe7,
	0xab, 0x0d, 0x9a, 0xb6, 0xb7, 0x36, 0x6d, 0xd7, 0xe5, 0xa1, 0x7d, 0x38, 0x10, 0xc4, 0x1a, 0xf6,
	0x12, 0x3a, 0x42, 0xf5, 0xda, 0x0e, 0xf0, 0xd9, 0x70, 0x82, 0x4b, 0xee, 0xa0, 0x85, 0x5f, 0xb6,
	0x18, 0x84, 0x5a, 0x17, 0xc0, 0x89, 0x0a, 0xce, 0x2c, 0xf4, 0xaf, 0x95, 0x07, 0xca, 0xa3, 0x86,
	0x45, 0x2a, 0xec, 0x05, 0x74, 0x8b, 0x1a, 0x04, 0x1e, 0x77, 0x03, 0xd4, 0x74, 0xb8, 0xeb, 0xdb,
	0xdf, 0x3e, 0xd9, 0x9b, 0x2d, 0x46, 0xfa, 0x7b, 0xd6, 0xe9, 0x3f, 0x7b, 0x2e, 0xdb, 0x4f, 0x5d,
	0x6a, 0x5f, 0x26, 0x7e, 0x25, 0x5b, 0x1f, 0xc5, 0x89, 0x75, 0x17, 0x00, 0xdd, 0x2c, 0xbc, 0xa8,
	0xb0, 0x37, 0xd0, 0x12, 0x1d, 0xe6, 0xf3, 0x8f, 0xd3, 0xf1, 0xd1, 0xf7, 0x1c, 0x6e, 0x7d, 0xc6,
	0x7d, 0x62, 0x79, 0xf8, 0x99, 0x22, 0x51, 0x33, 0x24, 0xef, 0xe1, 0x4a, 0xea, 0x93, 0x20, 0xc8,
	0x8d, 0x18, 0x34, 0x92, 0xa7, 0x8b, 0xb1, 0xd4, 0x08, 0x2b, 0x55, 0x63, 0xef, 0xa0, 0x35, 0xc1,
	0x9a, 0x60, 0x75, 0xfa, 0xbd, 0x85, 0x2b, 0xa9, 0x5f, 0x21, 0x60, 0xd9, 0x4d, 0xfb, 0x40, 0xb6,
	0xcc, 0x9a, 0x8d, 0xf3, 0xde, 0x49, 0x95, 0x1e, 0xf9, 0x32, 0xa3, 0x49, 0xac, 0xb3, 0xe4, 0x4a,
	0x0e, 0xf9, 0x08, 0x9a, 0x82, 0x9c, 0x18, 0xd6, 0xb9, 0xf5, 0x00, 0x2e, 0x33, 0xda, 0x9c, 0x95,
	0xcc, 0xd0, 0xf6, 0xbf, 0xdf, 0x81, 0x0b, 0x29, 0x48, 0xda, 0x1f, 0x05, 0x1a, 0x0b, 0xb2, 0x62,
	0xda, 0xc0, 0xc8, 0x4b, 0x9b, 0x51, 0xba, 0xcd, 0xfa, 0xf0, 0x66, 0xa2, 0x98, 0x96, 0x3d, 0xfc,
	0xf1, 0xf7, 0xdf, 0x6f, 0xb5, 0xc3, 0xae, 0x4d, 0x11, 0x79, 0x93, 0xc2, 0x8c, 0x94, 0x1e, 0x01,
	0x8c, 0xe3, 0x57, 0x17, 0x30, 0x95, 0xf6, 0xba, 0x80, 0xe9, 0x84, 0x97, 0x01, 0xc6, 0x27, 0x0f,
	0x80, 0xbf, 0x14, 0x38, 0xdb, 0xed, 0x42, 0xb4, 0x45, 0x33, 0xed, 0x49, 0x95, 0x1d, 0x5d, 0x7d,
	0xfd, 0x69, 0xcd, 0xd3, 0x09, 0x55, 0x3b, 0xa2, 0x6a, 0xb1, 0x0b, 0x4a, 0x15, 0x11, 0xa4, 0x70,
	0xc4, 0x86, 0x14, 0xe1, 0xe4, 0x27, 0xb1, 0x08, 0xa7, 0x20, 0x67, 0x04, 0xc7, 0x41, 0x19, 0xe7,
	0xa7, 0x02, 0xf7, 0xfd, 0x80, 0xce, 0xa6, 0x57, 0x75, 0x5b, 0x11, 0x06, 0xfd, 0x71, 0xad, 0xb3,
	0x09, 0x88, 0x1e, 0x81, 0x34, 0xd9, 0x19, 0x9d, 0x8b, 0x1f, 0x50, 0x0c, 0x32, 0x93, 0x5e, 0xd5,
	0x2d, 0xab, 0x31, 0x72, 0x33, 0x48, 0x30, 0xc8, 0x3c, 0x62, 0x8c, 0xc5, 0xed, 0xe8, 0xe3, 0x34,
	0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x19, 0x0f, 0x79, 0xe4, 0x06, 0x00, 0x00,
}
