// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

/*
Package Aphro_Room_pb is a generated protocol buffer package.

It is generated from these files:
	room.proto

It has these top-level messages:
	RSDeleteRequest
	RSDeleteResponse
	RSResult
	RSQueryRequest
	RSQueryResponse
	RSCreateRequest
	RSCreateResponse
	RSUpdateRequest
	RSUpdateResponse
	RSLocation
	RSTerminalBindRequest
	RSTerminalBindResponse
	RSTerminalUnbindRequest
	RSTerminalUnbindResponse
	RCRResult
	RCRDeleteRequest
	RCRDeleteResponse
	RCRQueryRequest
	RCRQueryResponse
	RCRUpdateRequest
	RCRUpdateResponse
	RCRCreateRequest
	RCRBatchCreateRequest
	RCRBatchCreateResponse
	RCRCreateResponse
	RSTransactionBeginRequest
	RSTransactionBeginResponse
	RSTransactionSuspendRequest
	RSTransactionSuspendResponse
	RSTransactionEndRequest
	RSTransactionEndResponse
	RSTransactionCreateRoomFeeRequest
	RSTransactionCreateRoomFeeResponse
	RSTransactionQueryRoomFeeRequest
	RSTransactionQueryRoomFeeResponse
	RSTransactionRoomFeeResult
*/
package Aphro_Room_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/wrappers"
import Aphro_CommonBiz "github.com/lampard1014/aphro/CommonBiz/Response/PB"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RSDeleteRequest struct {
	RoomID       uint32 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
}

func (m *RSDeleteRequest) Reset()                    { *m = RSDeleteRequest{} }
func (m *RSDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*RSDeleteRequest) ProtoMessage()               {}
func (*RSDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RSDeleteRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSDeleteRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type RSDeleteResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RSDeleteResponse) Reset()                    { *m = RSDeleteResponse{} }
func (m *RSDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*RSDeleteResponse) ProtoMessage()               {}
func (*RSDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RSDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSResult struct {
	RoomID       uint32       `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	MerchantID   uint32       `protobuf:"varint,2,opt,name=merchantID" json:"merchantID,omitempty"`
	TerminalCode string       `protobuf:"bytes,3,opt,name=terminalCode" json:"terminalCode,omitempty"`
	Location     *RSLocation  `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	Status       uint32       `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	RoomName     string       `protobuf:"bytes,6,opt,name=roomName" json:"roomName,omitempty"`
	Flag         uint32       `protobuf:"varint,8,opt,name=flag" json:"flag,omitempty"`
	ChargeRules  []*RCRResult `protobuf:"bytes,7,rep,name=chargeRules" json:"chargeRules,omitempty"`
}

func (m *RSResult) Reset()                    { *m = RSResult{} }
func (m *RSResult) String() string            { return proto.CompactTextString(m) }
func (*RSResult) ProtoMessage()               {}
func (*RSResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RSResult) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSResult) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RSResult) GetTerminalCode() string {
	if m != nil {
		return m.TerminalCode
	}
	return ""
}

func (m *RSResult) GetLocation() *RSLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RSResult) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RSResult) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RSResult) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *RSResult) GetChargeRules() []*RCRResult {
	if m != nil {
		return m.ChargeRules
	}
	return nil
}

type RSQueryRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID       uint32 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
	MerchantID   uint32 `protobuf:"varint,3,opt,name=merchantID" json:"merchantID,omitempty"`
}

func (m *RSQueryRequest) Reset()                    { *m = RSQueryRequest{} }
func (m *RSQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*RSQueryRequest) ProtoMessage()               {}
func (*RSQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RSQueryRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSQueryRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSQueryRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

type RSQueryResponse struct {
	Success bool        `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Rooms   []*RSResult `protobuf:"bytes,2,rep,name=rooms" json:"rooms,omitempty"`
}

func (m *RSQueryResponse) Reset()                    { *m = RSQueryResponse{} }
func (m *RSQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*RSQueryResponse) ProtoMessage()               {}
func (*RSQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RSQueryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RSQueryResponse) GetRooms() []*RSResult {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type RSCreateRequest struct {
	TerminalCode string      `protobuf:"bytes,1,opt,name=terminalCode" json:"terminalCode,omitempty"`
	SessionToken string      `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	Location     *RSLocation `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	RoomName     string      `protobuf:"bytes,4,opt,name=roomName" json:"roomName,omitempty"`
}

func (m *RSCreateRequest) Reset()                    { *m = RSCreateRequest{} }
func (m *RSCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*RSCreateRequest) ProtoMessage()               {}
func (*RSCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RSCreateRequest) GetTerminalCode() string {
	if m != nil {
		return m.TerminalCode
	}
	return ""
}

func (m *RSCreateRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSCreateRequest) GetLocation() *RSLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RSCreateRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type RSCreateResponse struct {
	RoomID  uint32 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *RSCreateResponse) Reset()                    { *m = RSCreateResponse{} }
func (m *RSCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*RSCreateResponse) ProtoMessage()               {}
func (*RSCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RSCreateResponse) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSUpdateRequest struct {
	SessionToken *google_protobuf1.StringValue `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID       *google_protobuf1.UInt32Value `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	TerminalCode *google_protobuf1.StringValue `protobuf:"bytes,3,opt,name=terminalCode" json:"terminalCode,omitempty"`
	Location     *RSLocation                   `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	Status       *google_protobuf1.UInt32Value `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	RoomName     *google_protobuf1.StringValue `protobuf:"bytes,7,opt,name=roomName" json:"roomName,omitempty"`
}

func (m *RSUpdateRequest) Reset()                    { *m = RSUpdateRequest{} }
func (m *RSUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*RSUpdateRequest) ProtoMessage()               {}
func (*RSUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RSUpdateRequest) GetSessionToken() *google_protobuf1.StringValue {
	if m != nil {
		return m.SessionToken
	}
	return nil
}

func (m *RSUpdateRequest) GetRoomID() *google_protobuf1.UInt32Value {
	if m != nil {
		return m.RoomID
	}
	return nil
}

func (m *RSUpdateRequest) GetTerminalCode() *google_protobuf1.StringValue {
	if m != nil {
		return m.TerminalCode
	}
	return nil
}

func (m *RSUpdateRequest) GetLocation() *RSLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RSUpdateRequest) GetStatus() *google_protobuf1.UInt32Value {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RSUpdateRequest) GetRoomName() *google_protobuf1.StringValue {
	if m != nil {
		return m.RoomName
	}
	return nil
}

type RSUpdateResponse struct {
	Success bool `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *RSUpdateResponse) Reset()                    { *m = RSUpdateResponse{} }
func (m *RSUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*RSUpdateResponse) ProtoMessage()               {}
func (*RSUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RSUpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSLocation struct {
	Longitude string `protobuf:"bytes,1,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  string `protobuf:"bytes,2,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *RSLocation) Reset()                    { *m = RSLocation{} }
func (m *RSLocation) String() string            { return proto.CompactTextString(m) }
func (*RSLocation) ProtoMessage()               {}
func (*RSLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RSLocation) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *RSLocation) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

type RSTerminalBindRequest struct {
	SessionToken string      `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	TerminalCode string      `protobuf:"bytes,2,opt,name=terminalCode" json:"terminalCode,omitempty"`
	Location     *RSLocation `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	RoomID       uint32      `protobuf:"varint,4,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *RSTerminalBindRequest) Reset()                    { *m = RSTerminalBindRequest{} }
func (m *RSTerminalBindRequest) String() string            { return proto.CompactTextString(m) }
func (*RSTerminalBindRequest) ProtoMessage()               {}
func (*RSTerminalBindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RSTerminalBindRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSTerminalBindRequest) GetTerminalCode() string {
	if m != nil {
		return m.TerminalCode
	}
	return ""
}

func (m *RSTerminalBindRequest) GetLocation() *RSLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RSTerminalBindRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type RSTerminalBindResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RSTerminalBindResponse) Reset()                    { *m = RSTerminalBindResponse{} }
func (m *RSTerminalBindResponse) String() string            { return proto.CompactTextString(m) }
func (*RSTerminalBindResponse) ProtoMessage()               {}
func (*RSTerminalBindResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RSTerminalBindResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSTerminalUnbindRequest struct {
	RoomID       uint32 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
}

func (m *RSTerminalUnbindRequest) Reset()                    { *m = RSTerminalUnbindRequest{} }
func (m *RSTerminalUnbindRequest) String() string            { return proto.CompactTextString(m) }
func (*RSTerminalUnbindRequest) ProtoMessage()               {}
func (*RSTerminalUnbindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RSTerminalUnbindRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSTerminalUnbindRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type RSTerminalUnbindResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RSTerminalUnbindResponse) Reset()                    { *m = RSTerminalUnbindResponse{} }
func (m *RSTerminalUnbindResponse) String() string            { return proto.CompactTextString(m) }
func (*RSTerminalUnbindResponse) ProtoMessage()               {}
func (*RSTerminalUnbindResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RSTerminalUnbindResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// 房间计费方式
type RCRResult struct {
	MerchantID   uint32  `protobuf:"varint,1,opt,name=merchantID" json:"merchantID,omitempty"`
	RCRID        uint32  `protobuf:"varint,7,opt,name=RCRID" json:"RCRID,omitempty"`
	Fee          float32 `protobuf:"fixed32,2,opt,name=fee" json:"fee,omitempty"`
	Start        string  `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End          string  `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Interval     uint32  `protobuf:"varint,5,opt,name=interval" json:"interval,omitempty"`
	IntervalUnit uint32  `protobuf:"varint,6,opt,name=intervalUnit" json:"intervalUnit,omitempty"`
	RoomID       uint32  `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
	Flag         uint32  `protobuf:"varint,9,opt,name=flag" json:"flag,omitempty"`
	Name         string  `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
}

func (m *RCRResult) Reset()                    { *m = RCRResult{} }
func (m *RCRResult) String() string            { return proto.CompactTextString(m) }
func (*RCRResult) ProtoMessage()               {}
func (*RCRResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RCRResult) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RCRResult) GetRCRID() uint32 {
	if m != nil {
		return m.RCRID
	}
	return 0
}

func (m *RCRResult) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RCRResult) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *RCRResult) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *RCRResult) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *RCRResult) GetIntervalUnit() uint32 {
	if m != nil {
		return m.IntervalUnit
	}
	return 0
}

func (m *RCRResult) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RCRResult) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *RCRResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RCRDeleteRequest struct {
	MerchantID   uint32 `protobuf:"varint,1,opt,name=merchantID" json:"merchantID,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RCRID        uint32 `protobuf:"varint,7,opt,name=RCRID" json:"RCRID,omitempty"`
	RoomID       uint32 `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *RCRDeleteRequest) Reset()                    { *m = RCRDeleteRequest{} }
func (m *RCRDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*RCRDeleteRequest) ProtoMessage()               {}
func (*RCRDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RCRDeleteRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RCRDeleteRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RCRDeleteRequest) GetRCRID() uint32 {
	if m != nil {
		return m.RCRID
	}
	return 0
}

func (m *RCRDeleteRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type RCRDeleteResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RCRDeleteResponse) Reset()                    { *m = RCRDeleteResponse{} }
func (m *RCRDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*RCRDeleteResponse) ProtoMessage()               {}
func (*RCRDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RCRDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RCRQueryRequest struct {
	RCRID        uint32 `protobuf:"varint,1,opt,name=RCRID" json:"RCRID,omitempty"`
	SessionToken string `protobuf:"bytes,4,opt,name=sessionToken" json:"sessionToken,omitempty"`
	MerchantID   uint32 `protobuf:"varint,2,opt,name=merchantID" json:"merchantID,omitempty"`
	RoomID       uint32 `protobuf:"varint,3,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *RCRQueryRequest) Reset()                    { *m = RCRQueryRequest{} }
func (m *RCRQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*RCRQueryRequest) ProtoMessage()               {}
func (*RCRQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RCRQueryRequest) GetRCRID() uint32 {
	if m != nil {
		return m.RCRID
	}
	return 0
}

func (m *RCRQueryRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RCRQueryRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RCRQueryRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type RCRQueryResponse struct {
	Success bool         `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Results []*RCRResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *RCRQueryResponse) Reset()                    { *m = RCRQueryResponse{} }
func (m *RCRQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*RCRQueryResponse) ProtoMessage()               {}
func (*RCRQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *RCRQueryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RCRQueryResponse) GetResults() []*RCRResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type RCRUpdateRequest struct {
	MerchantID   uint32  `protobuf:"varint,1,opt,name=merchantID" json:"merchantID,omitempty"`
	RCRID        uint32  `protobuf:"varint,7,opt,name=RCRID" json:"RCRID,omitempty"`
	SessionToken string  `protobuf:"bytes,9,opt,name=sessionToken" json:"sessionToken,omitempty"`
	Fee          float32 `protobuf:"fixed32,2,opt,name=fee" json:"fee,omitempty"`
	Start        string  `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End          string  `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Interval     uint32  `protobuf:"varint,5,opt,name=interval" json:"interval,omitempty"`
	IntervalUnit uint32  `protobuf:"varint,6,opt,name=intervalUnit" json:"intervalUnit,omitempty"`
	RoomID       uint32  `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
	Name         string  `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
}

func (m *RCRUpdateRequest) Reset()                    { *m = RCRUpdateRequest{} }
func (m *RCRUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*RCRUpdateRequest) ProtoMessage()               {}
func (*RCRUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RCRUpdateRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RCRUpdateRequest) GetRCRID() uint32 {
	if m != nil {
		return m.RCRID
	}
	return 0
}

func (m *RCRUpdateRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RCRUpdateRequest) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RCRUpdateRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *RCRUpdateRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *RCRUpdateRequest) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *RCRUpdateRequest) GetIntervalUnit() uint32 {
	if m != nil {
		return m.IntervalUnit
	}
	return 0
}

func (m *RCRUpdateRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RCRUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RCRUpdateResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RCRUpdateResponse) Reset()                    { *m = RCRUpdateResponse{} }
func (m *RCRUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*RCRUpdateResponse) ProtoMessage()               {}
func (*RCRUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RCRUpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RCRCreateRequest struct {
	RcrID        uint32  `protobuf:"varint,11,opt,name=rcrID" json:"rcrID,omitempty"`
	SessionToken string  `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	Fee          float32 `protobuf:"fixed32,2,opt,name=fee" json:"fee,omitempty"`
	Start        string  `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End          string  `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Interval     uint32  `protobuf:"varint,5,opt,name=interval" json:"interval,omitempty"`
	IntervalUnit uint32  `protobuf:"varint,6,opt,name=intervalUnit" json:"intervalUnit,omitempty"`
	MerchantID   uint32  `protobuf:"varint,7,opt,name=merchantID" json:"merchantID,omitempty"`
	RoomID       uint32  `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
	Flag         uint32  `protobuf:"varint,9,opt,name=flag" json:"flag,omitempty"`
	Name         string  `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
}

func (m *RCRCreateRequest) Reset()                    { *m = RCRCreateRequest{} }
func (m *RCRCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*RCRCreateRequest) ProtoMessage()               {}
func (*RCRCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RCRCreateRequest) GetRcrID() uint32 {
	if m != nil {
		return m.RcrID
	}
	return 0
}

func (m *RCRCreateRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RCRCreateRequest) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RCRCreateRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *RCRCreateRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *RCRCreateRequest) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *RCRCreateRequest) GetIntervalUnit() uint32 {
	if m != nil {
		return m.IntervalUnit
	}
	return 0
}

func (m *RCRCreateRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RCRCreateRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RCRCreateRequest) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *RCRCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RCRBatchCreateRequest struct {
	SessionToken string              `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	MerchantID   uint32              `protobuf:"varint,2,opt,name=merchantID" json:"merchantID,omitempty"`
	RoomID       uint32              `protobuf:"varint,3,opt,name=roomID" json:"roomID,omitempty"`
	Rules        []*RCRCreateRequest `protobuf:"bytes,4,rep,name=rules" json:"rules,omitempty"`
}

func (m *RCRBatchCreateRequest) Reset()                    { *m = RCRBatchCreateRequest{} }
func (m *RCRBatchCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*RCRBatchCreateRequest) ProtoMessage()               {}
func (*RCRBatchCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RCRBatchCreateRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RCRBatchCreateRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RCRBatchCreateRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RCRBatchCreateRequest) GetRules() []*RCRCreateRequest {
	if m != nil {
		return m.Rules
	}
	return nil
}

type RCRBatchCreateResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RCRBatchCreateResponse) Reset()                    { *m = RCRBatchCreateResponse{} }
func (m *RCRBatchCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*RCRBatchCreateResponse) ProtoMessage()               {}
func (*RCRBatchCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RCRBatchCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RCRCreateResponse struct {
	Success  bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	RecodeID uint32 `protobuf:"varint,2,opt,name=recodeID" json:"recodeID,omitempty"`
}

func (m *RCRCreateResponse) Reset()                    { *m = RCRCreateResponse{} }
func (m *RCRCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*RCRCreateResponse) ProtoMessage()               {}
func (*RCRCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RCRCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RCRCreateResponse) GetRecodeID() uint32 {
	if m != nil {
		return m.RecodeID
	}
	return 0
}

type RSTransactionBeginRequest struct {
	SessionToken    string              `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID          uint32              `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
	RoomChargeRules []*RCRCreateRequest `protobuf:"bytes,3,rep,name=roomChargeRules" json:"roomChargeRules,omitempty"`
}

func (m *RSTransactionBeginRequest) Reset()                    { *m = RSTransactionBeginRequest{} }
func (m *RSTransactionBeginRequest) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionBeginRequest) ProtoMessage()               {}
func (*RSTransactionBeginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *RSTransactionBeginRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSTransactionBeginRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSTransactionBeginRequest) GetRoomChargeRules() []*RCRCreateRequest {
	if m != nil {
		return m.RoomChargeRules
	}
	return nil
}

type RSTransactionBeginResponse struct {
	Success       bool    `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	TransactionID uint32  `protobuf:"varint,2,opt,name=transactionID" json:"transactionID,omitempty"`
	Start         uint64  `protobuf:"varint,3,opt,name=start" json:"start,omitempty"`
	Fee           float32 `protobuf:"fixed32,4,opt,name=fee" json:"fee,omitempty"`
}

func (m *RSTransactionBeginResponse) Reset()                    { *m = RSTransactionBeginResponse{} }
func (m *RSTransactionBeginResponse) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionBeginResponse) ProtoMessage()               {}
func (*RSTransactionBeginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *RSTransactionBeginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RSTransactionBeginResponse) GetTransactionID() uint32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *RSTransactionBeginResponse) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *RSTransactionBeginResponse) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type RSTransactionSuspendRequest struct {
	SessionToken  string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID        uint32 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
	TransactionID uint32 `protobuf:"varint,3,opt,name=transactionID" json:"transactionID,omitempty"`
}

func (m *RSTransactionSuspendRequest) Reset()                    { *m = RSTransactionSuspendRequest{} }
func (m *RSTransactionSuspendRequest) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionSuspendRequest) ProtoMessage()               {}
func (*RSTransactionSuspendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *RSTransactionSuspendRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSTransactionSuspendRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSTransactionSuspendRequest) GetTransactionID() uint32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

type RSTransactionSuspendResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RSTransactionSuspendResponse) Reset()                    { *m = RSTransactionSuspendResponse{} }
func (m *RSTransactionSuspendResponse) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionSuspendResponse) ProtoMessage()               {}
func (*RSTransactionSuspendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *RSTransactionSuspendResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSTransactionEndRequest struct {
	SessionToken  string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RoomID        uint32 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
	TransactionID uint32 `protobuf:"varint,3,opt,name=transactionID" json:"transactionID,omitempty"`
	MerchantID    uint32 `protobuf:"varint,4,opt,name=merchantID" json:"merchantID,omitempty"`
}

func (m *RSTransactionEndRequest) Reset()                    { *m = RSTransactionEndRequest{} }
func (m *RSTransactionEndRequest) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionEndRequest) ProtoMessage()               {}
func (*RSTransactionEndRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *RSTransactionEndRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSTransactionEndRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSTransactionEndRequest) GetTransactionID() uint32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *RSTransactionEndRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

type RSTransactionEndResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RSTransactionEndResponse) Reset()                    { *m = RSTransactionEndResponse{} }
func (m *RSTransactionEndResponse) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionEndResponse) ProtoMessage()               {}
func (*RSTransactionEndResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *RSTransactionEndResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSTransactionCreateRoomFeeRequest struct {
	SessionToken  string  `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	Fee           float32 `protobuf:"fixed32,2,opt,name=fee" json:"fee,omitempty"`
	Start         string  `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End           string  `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Interval      uint32  `protobuf:"varint,5,opt,name=interval" json:"interval,omitempty"`
	IntervalUnit  uint32  `protobuf:"varint,6,opt,name=intervalUnit" json:"intervalUnit,omitempty"`
	MerchantID    uint32  `protobuf:"varint,7,opt,name=merchantID" json:"merchantID,omitempty"`
	RoomID        uint32  `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
	TransactionID uint32  `protobuf:"varint,9,opt,name=transactionID" json:"transactionID,omitempty"`
	Flag          uint32  `protobuf:"varint,10,opt,name=flag" json:"flag,omitempty"`
}

func (m *RSTransactionCreateRoomFeeRequest) Reset()         { *m = RSTransactionCreateRoomFeeRequest{} }
func (m *RSTransactionCreateRoomFeeRequest) String() string { return proto.CompactTextString(m) }
func (*RSTransactionCreateRoomFeeRequest) ProtoMessage()    {}
func (*RSTransactionCreateRoomFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{31}
}

func (m *RSTransactionCreateRoomFeeRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSTransactionCreateRoomFeeRequest) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RSTransactionCreateRoomFeeRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *RSTransactionCreateRoomFeeRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *RSTransactionCreateRoomFeeRequest) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *RSTransactionCreateRoomFeeRequest) GetIntervalUnit() uint32 {
	if m != nil {
		return m.IntervalUnit
	}
	return 0
}

func (m *RSTransactionCreateRoomFeeRequest) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RSTransactionCreateRoomFeeRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSTransactionCreateRoomFeeRequest) GetTransactionID() uint32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *RSTransactionCreateRoomFeeRequest) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type RSTransactionCreateRoomFeeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RSTransactionCreateRoomFeeResponse) Reset()         { *m = RSTransactionCreateRoomFeeResponse{} }
func (m *RSTransactionCreateRoomFeeResponse) String() string { return proto.CompactTextString(m) }
func (*RSTransactionCreateRoomFeeResponse) ProtoMessage()    {}
func (*RSTransactionCreateRoomFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{32}
}

func (m *RSTransactionCreateRoomFeeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RSTransactionQueryRoomFeeRequest struct {
	SessionToken         string `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	TransactionID        uint32 `protobuf:"varint,9,opt,name=transactionID" json:"transactionID,omitempty"`
	TransactionRoomFeeID uint32 `protobuf:"varint,2,opt,name=transactionRoomFeeID" json:"transactionRoomFeeID,omitempty"`
	RoomID               uint32 `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *RSTransactionQueryRoomFeeRequest) Reset()         { *m = RSTransactionQueryRoomFeeRequest{} }
func (m *RSTransactionQueryRoomFeeRequest) String() string { return proto.CompactTextString(m) }
func (*RSTransactionQueryRoomFeeRequest) ProtoMessage()    {}
func (*RSTransactionQueryRoomFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33}
}

func (m *RSTransactionQueryRoomFeeRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RSTransactionQueryRoomFeeRequest) GetTransactionID() uint32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *RSTransactionQueryRoomFeeRequest) GetTransactionRoomFeeID() uint32 {
	if m != nil {
		return m.TransactionRoomFeeID
	}
	return 0
}

func (m *RSTransactionQueryRoomFeeRequest) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type RSTransactionQueryRoomFeeResponse struct {
	Success  bool                          `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	RoomFees []*RSTransactionRoomFeeResult `protobuf:"bytes,2,rep,name=roomFees" json:"roomFees,omitempty"`
}

func (m *RSTransactionQueryRoomFeeResponse) Reset()         { *m = RSTransactionQueryRoomFeeResponse{} }
func (m *RSTransactionQueryRoomFeeResponse) String() string { return proto.CompactTextString(m) }
func (*RSTransactionQueryRoomFeeResponse) ProtoMessage()    {}
func (*RSTransactionQueryRoomFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{34}
}

func (m *RSTransactionQueryRoomFeeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RSTransactionQueryRoomFeeResponse) GetRoomFees() []*RSTransactionRoomFeeResult {
	if m != nil {
		return m.RoomFees
	}
	return nil
}

type RSTransactionRoomFeeResult struct {
	TransactionRoomFeeID uint32  `protobuf:"varint,1,opt,name=transactionRoomFeeID" json:"transactionRoomFeeID,omitempty"`
	Fee                  float32 `protobuf:"fixed32,2,opt,name=fee" json:"fee,omitempty"`
	CreateTime           uint32  `protobuf:"varint,12,opt,name=createTime" json:"createTime,omitempty"`
	EndTime              uint32  `protobuf:"varint,13,opt,name=endTime" json:"endTime,omitempty"`
	FeePerInterval       float32 `protobuf:"fixed32,11,opt,name=feePerInterval" json:"feePerInterval,omitempty"`
	Start                string  `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End                  string  `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Interval             uint32  `protobuf:"varint,5,opt,name=interval" json:"interval,omitempty"`
	IntervalUnit         uint32  `protobuf:"varint,6,opt,name=intervalUnit" json:"intervalUnit,omitempty"`
	MerchantID           uint32  `protobuf:"varint,7,opt,name=merchantID" json:"merchantID,omitempty"`
	RoomID               uint32  `protobuf:"varint,8,opt,name=roomID" json:"roomID,omitempty"`
	TransactionID        uint32  `protobuf:"varint,9,opt,name=transactionID" json:"transactionID,omitempty"`
	Flag                 uint32  `protobuf:"varint,10,opt,name=flag" json:"flag,omitempty"`
}

func (m *RSTransactionRoomFeeResult) Reset()                    { *m = RSTransactionRoomFeeResult{} }
func (m *RSTransactionRoomFeeResult) String() string            { return proto.CompactTextString(m) }
func (*RSTransactionRoomFeeResult) ProtoMessage()               {}
func (*RSTransactionRoomFeeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *RSTransactionRoomFeeResult) GetTransactionRoomFeeID() uint32 {
	if m != nil {
		return m.TransactionRoomFeeID
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetFeePerInterval() float32 {
	if m != nil {
		return m.FeePerInterval
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *RSTransactionRoomFeeResult) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *RSTransactionRoomFeeResult) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetIntervalUnit() uint32 {
	if m != nil {
		return m.IntervalUnit
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetMerchantID() uint32 {
	if m != nil {
		return m.MerchantID
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetTransactionID() uint32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *RSTransactionRoomFeeResult) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func init() {
	proto.RegisterType((*RSDeleteRequest)(nil), "Aphro.Room.pb.RSDeleteRequest")
	proto.RegisterType((*RSDeleteResponse)(nil), "Aphro.Room.pb.RSDeleteResponse")
	proto.RegisterType((*RSResult)(nil), "Aphro.Room.pb.RSResult")
	proto.RegisterType((*RSQueryRequest)(nil), "Aphro.Room.pb.RSQueryRequest")
	proto.RegisterType((*RSQueryResponse)(nil), "Aphro.Room.pb.RSQueryResponse")
	proto.RegisterType((*RSCreateRequest)(nil), "Aphro.Room.pb.RSCreateRequest")
	proto.RegisterType((*RSCreateResponse)(nil), "Aphro.Room.pb.RSCreateResponse")
	proto.RegisterType((*RSUpdateRequest)(nil), "Aphro.Room.pb.RSUpdateRequest")
	proto.RegisterType((*RSUpdateResponse)(nil), "Aphro.Room.pb.RSUpdateResponse")
	proto.RegisterType((*RSLocation)(nil), "Aphro.Room.pb.RSLocation")
	proto.RegisterType((*RSTerminalBindRequest)(nil), "Aphro.Room.pb.RSTerminalBindRequest")
	proto.RegisterType((*RSTerminalBindResponse)(nil), "Aphro.Room.pb.RSTerminalBindResponse")
	proto.RegisterType((*RSTerminalUnbindRequest)(nil), "Aphro.Room.pb.RSTerminalUnbindRequest")
	proto.RegisterType((*RSTerminalUnbindResponse)(nil), "Aphro.Room.pb.RSTerminalUnbindResponse")
	proto.RegisterType((*RCRResult)(nil), "Aphro.Room.pb.RCRResult")
	proto.RegisterType((*RCRDeleteRequest)(nil), "Aphro.Room.pb.RCRDeleteRequest")
	proto.RegisterType((*RCRDeleteResponse)(nil), "Aphro.Room.pb.RCRDeleteResponse")
	proto.RegisterType((*RCRQueryRequest)(nil), "Aphro.Room.pb.RCRQueryRequest")
	proto.RegisterType((*RCRQueryResponse)(nil), "Aphro.Room.pb.RCRQueryResponse")
	proto.RegisterType((*RCRUpdateRequest)(nil), "Aphro.Room.pb.RCRUpdateRequest")
	proto.RegisterType((*RCRUpdateResponse)(nil), "Aphro.Room.pb.RCRUpdateResponse")
	proto.RegisterType((*RCRCreateRequest)(nil), "Aphro.Room.pb.RCRCreateRequest")
	proto.RegisterType((*RCRBatchCreateRequest)(nil), "Aphro.Room.pb.RCRBatchCreateRequest")
	proto.RegisterType((*RCRBatchCreateResponse)(nil), "Aphro.Room.pb.RCRBatchCreateResponse")
	proto.RegisterType((*RCRCreateResponse)(nil), "Aphro.Room.pb.RCRCreateResponse")
	proto.RegisterType((*RSTransactionBeginRequest)(nil), "Aphro.Room.pb.RSTransactionBeginRequest")
	proto.RegisterType((*RSTransactionBeginResponse)(nil), "Aphro.Room.pb.RSTransactionBeginResponse")
	proto.RegisterType((*RSTransactionSuspendRequest)(nil), "Aphro.Room.pb.RSTransactionSuspendRequest")
	proto.RegisterType((*RSTransactionSuspendResponse)(nil), "Aphro.Room.pb.RSTransactionSuspendResponse")
	proto.RegisterType((*RSTransactionEndRequest)(nil), "Aphro.Room.pb.RSTransactionEndRequest")
	proto.RegisterType((*RSTransactionEndResponse)(nil), "Aphro.Room.pb.RSTransactionEndResponse")
	proto.RegisterType((*RSTransactionCreateRoomFeeRequest)(nil), "Aphro.Room.pb.RSTransactionCreateRoomFeeRequest")
	proto.RegisterType((*RSTransactionCreateRoomFeeResponse)(nil), "Aphro.Room.pb.RSTransactionCreateRoomFeeResponse")
	proto.RegisterType((*RSTransactionQueryRoomFeeRequest)(nil), "Aphro.Room.pb.RSTransactionQueryRoomFeeRequest")
	proto.RegisterType((*RSTransactionQueryRoomFeeResponse)(nil), "Aphro.Room.pb.RSTransactionQueryRoomFeeResponse")
	proto.RegisterType((*RSTransactionRoomFeeResult)(nil), "Aphro.Room.pb.RSTransactionRoomFeeResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RoomService service

type RoomServiceClient interface {
	// 绑定二维码终端信息
	TerminalBind(ctx context.Context, in *RSTerminalBindRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 解绑二维码终端信息
	TerminalUnbind(ctx context.Context, in *RSTerminalUnbindRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 直接创建房间 同时绑定二维码
	CreateRoom(ctx context.Context, in *RSCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 更新房间的信息 同时更新计费方式
	UpdateRoom(ctx context.Context, in *RSUpdateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 删除房间
	DeleteRoom(ctx context.Context, in *RSDeleteRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 查询房间
	QueryRoom(ctx context.Context, in *RSQueryRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 创建计费方式
	CreateRoomChargeRule(ctx context.Context, in *RCRCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 批量创建计费方式
	BatchCreateRoomChargeRule(ctx context.Context, in *RCRBatchCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 更新计费方式
	UpdateRoomChargeRule(ctx context.Context, in *RCRUpdateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 查询计费方式
	QueryRoomChargeRule(ctx context.Context, in *RCRQueryRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 删除计费方式
	DeleteRoomChargeRule(ctx context.Context, in *RCRDeleteRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 开始一个房间的事务
	RoomTransactionBegin(ctx context.Context, in *RSTransactionBeginRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 挂起一个房间的事务
	RoomTransactionSuspend(ctx context.Context, in *RSTransactionSuspendRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 结束一个房间的事务
	RoomTransactionEnd(ctx context.Context, in *RSTransactionEndRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 创建一个房间的房费
	RoomTransactionCreateRoomFee(ctx context.Context, in *RSTransactionCreateRoomFeeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
	// 查询一个房间的房费
	RoomTransactionQueryRoomFee(ctx context.Context, in *RSTransactionQueryRoomFeeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) TerminalBind(ctx context.Context, in *RSTerminalBindRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/terminalBind", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) TerminalUnbind(ctx context.Context, in *RSTerminalUnbindRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/terminalUnbind", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *RSCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/createRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoom(ctx context.Context, in *RSUpdateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/updateRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DeleteRoom(ctx context.Context, in *RSDeleteRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/deleteRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) QueryRoom(ctx context.Context, in *RSQueryRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/queryRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) CreateRoomChargeRule(ctx context.Context, in *RCRCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/createRoomChargeRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) BatchCreateRoomChargeRule(ctx context.Context, in *RCRBatchCreateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/batchCreateRoomChargeRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoomChargeRule(ctx context.Context, in *RCRUpdateRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/updateRoomChargeRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) QueryRoomChargeRule(ctx context.Context, in *RCRQueryRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/queryRoomChargeRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DeleteRoomChargeRule(ctx context.Context, in *RCRDeleteRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/deleteRoomChargeRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RoomTransactionBegin(ctx context.Context, in *RSTransactionBeginRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/roomTransactionBegin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RoomTransactionSuspend(ctx context.Context, in *RSTransactionSuspendRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/roomTransactionSuspend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RoomTransactionEnd(ctx context.Context, in *RSTransactionEndRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/roomTransactionEnd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RoomTransactionCreateRoomFee(ctx context.Context, in *RSTransactionCreateRoomFeeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/roomTransactionCreateRoomFee", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) RoomTransactionQueryRoomFee(ctx context.Context, in *RSTransactionQueryRoomFeeRequest, opts ...grpc.CallOption) (*Aphro_CommonBiz.Response, error) {
	out := new(Aphro_CommonBiz.Response)
	err := grpc.Invoke(ctx, "/Aphro.Room.pb.RoomService/roomTransactionQueryRoomFee", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomService service

type RoomServiceServer interface {
	// 绑定二维码终端信息
	TerminalBind(context.Context, *RSTerminalBindRequest) (*Aphro_CommonBiz.Response, error)
	// 解绑二维码终端信息
	TerminalUnbind(context.Context, *RSTerminalUnbindRequest) (*Aphro_CommonBiz.Response, error)
	// 直接创建房间 同时绑定二维码
	CreateRoom(context.Context, *RSCreateRequest) (*Aphro_CommonBiz.Response, error)
	// 更新房间的信息 同时更新计费方式
	UpdateRoom(context.Context, *RSUpdateRequest) (*Aphro_CommonBiz.Response, error)
	// 删除房间
	DeleteRoom(context.Context, *RSDeleteRequest) (*Aphro_CommonBiz.Response, error)
	// 查询房间
	QueryRoom(context.Context, *RSQueryRequest) (*Aphro_CommonBiz.Response, error)
	// 创建计费方式
	CreateRoomChargeRule(context.Context, *RCRCreateRequest) (*Aphro_CommonBiz.Response, error)
	// 批量创建计费方式
	BatchCreateRoomChargeRule(context.Context, *RCRBatchCreateRequest) (*Aphro_CommonBiz.Response, error)
	// 更新计费方式
	UpdateRoomChargeRule(context.Context, *RCRUpdateRequest) (*Aphro_CommonBiz.Response, error)
	// 查询计费方式
	QueryRoomChargeRule(context.Context, *RCRQueryRequest) (*Aphro_CommonBiz.Response, error)
	// 删除计费方式
	DeleteRoomChargeRule(context.Context, *RCRDeleteRequest) (*Aphro_CommonBiz.Response, error)
	// 开始一个房间的事务
	RoomTransactionBegin(context.Context, *RSTransactionBeginRequest) (*Aphro_CommonBiz.Response, error)
	// 挂起一个房间的事务
	RoomTransactionSuspend(context.Context, *RSTransactionSuspendRequest) (*Aphro_CommonBiz.Response, error)
	// 结束一个房间的事务
	RoomTransactionEnd(context.Context, *RSTransactionEndRequest) (*Aphro_CommonBiz.Response, error)
	// 创建一个房间的房费
	RoomTransactionCreateRoomFee(context.Context, *RSTransactionCreateRoomFeeRequest) (*Aphro_CommonBiz.Response, error)
	// 查询一个房间的房费
	RoomTransactionQueryRoomFee(context.Context, *RSTransactionQueryRoomFeeRequest) (*Aphro_CommonBiz.Response, error)
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_TerminalBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTerminalBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).TerminalBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/TerminalBind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).TerminalBind(ctx, req.(*RSTerminalBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_TerminalUnbind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTerminalUnbindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).TerminalUnbind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/TerminalUnbind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).TerminalUnbind(ctx, req.(*RSTerminalUnbindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*RSCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/UpdateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoom(ctx, req.(*RSUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/DeleteRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DeleteRoom(ctx, req.(*RSDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_QueryRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).QueryRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/QueryRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).QueryRoom(ctx, req.(*RSQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_CreateRoomChargeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RCRCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoomChargeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/CreateRoomChargeRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoomChargeRule(ctx, req.(*RCRCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_BatchCreateRoomChargeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RCRBatchCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).BatchCreateRoomChargeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/BatchCreateRoomChargeRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).BatchCreateRoomChargeRule(ctx, req.(*RCRBatchCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoomChargeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RCRUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoomChargeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/UpdateRoomChargeRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoomChargeRule(ctx, req.(*RCRUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_QueryRoomChargeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RCRQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).QueryRoomChargeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/QueryRoomChargeRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).QueryRoomChargeRule(ctx, req.(*RCRQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DeleteRoomChargeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RCRDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DeleteRoomChargeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/DeleteRoomChargeRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DeleteRoomChargeRule(ctx, req.(*RCRDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RoomTransactionBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTransactionBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomTransactionBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/RoomTransactionBegin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomTransactionBegin(ctx, req.(*RSTransactionBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RoomTransactionSuspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTransactionSuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomTransactionSuspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/RoomTransactionSuspend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomTransactionSuspend(ctx, req.(*RSTransactionSuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RoomTransactionEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTransactionEndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomTransactionEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/RoomTransactionEnd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomTransactionEnd(ctx, req.(*RSTransactionEndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RoomTransactionCreateRoomFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTransactionCreateRoomFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomTransactionCreateRoomFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/RoomTransactionCreateRoomFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomTransactionCreateRoomFee(ctx, req.(*RSTransactionCreateRoomFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_RoomTransactionQueryRoomFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSTransactionQueryRoomFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RoomTransactionQueryRoomFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aphro.Room.pb.RoomService/RoomTransactionQueryRoomFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RoomTransactionQueryRoomFee(ctx, req.(*RSTransactionQueryRoomFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Aphro.Room.pb.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "terminalBind",
			Handler:    _RoomService_TerminalBind_Handler,
		},
		{
			MethodName: "terminalUnbind",
			Handler:    _RoomService_TerminalUnbind_Handler,
		},
		{
			MethodName: "createRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "updateRoom",
			Handler:    _RoomService_UpdateRoom_Handler,
		},
		{
			MethodName: "deleteRoom",
			Handler:    _RoomService_DeleteRoom_Handler,
		},
		{
			MethodName: "queryRoom",
			Handler:    _RoomService_QueryRoom_Handler,
		},
		{
			MethodName: "createRoomChargeRule",
			Handler:    _RoomService_CreateRoomChargeRule_Handler,
		},
		{
			MethodName: "batchCreateRoomChargeRule",
			Handler:    _RoomService_BatchCreateRoomChargeRule_Handler,
		},
		{
			MethodName: "updateRoomChargeRule",
			Handler:    _RoomService_UpdateRoomChargeRule_Handler,
		},
		{
			MethodName: "queryRoomChargeRule",
			Handler:    _RoomService_QueryRoomChargeRule_Handler,
		},
		{
			MethodName: "deleteRoomChargeRule",
			Handler:    _RoomService_DeleteRoomChargeRule_Handler,
		},
		{
			MethodName: "roomTransactionBegin",
			Handler:    _RoomService_RoomTransactionBegin_Handler,
		},
		{
			MethodName: "roomTransactionSuspend",
			Handler:    _RoomService_RoomTransactionSuspend_Handler,
		},
		{
			MethodName: "roomTransactionEnd",
			Handler:    _RoomService_RoomTransactionEnd_Handler,
		},
		{
			MethodName: "roomTransactionCreateRoomFee",
			Handler:    _RoomService_RoomTransactionCreateRoomFee_Handler,
		},
		{
			MethodName: "roomTransactionQueryRoomFee",
			Handler:    _RoomService_RoomTransactionQueryRoomFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room.proto",
}

func init() { proto.RegisterFile("room.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0xd6, 0xda, 0x4e, 0x93, 0x1c, 0x37, 0x6d, 0xba, 0x4d, 0x93, 0x4d, 0x9a, 0xa6, 0x79, 0xa7,
	0x51, 0x95, 0x46, 0x6f, 0xbd, 0xad, 0x9b, 0x4a, 0x7d, 0x7b, 0xf1, 0xaa, 0x8d, 0xd3, 0x4a, 0x96,
	0x00, 0x95, 0x71, 0xc2, 0x05, 0x12, 0xa2, 0x6b, 0x7b, 0xe2, 0xac, 0x58, 0xef, 0xba, 0xfb, 0xd1,
	0xaa, 0x20, 0x54, 0x09, 0x0a, 0x3f, 0x00, 0x90, 0xb8, 0x40, 0x42, 0xa2, 0x17, 0x5c, 0x20, 0xc4,
	0x0d, 0x37, 0xfc, 0x0f, 0xfe, 0x02, 0xbf, 0x80, 0x5b, 0x6e, 0xd0, 0xcc, 0xec, 0xc7, 0xcc, 0xee,
	0x7a, 0xd7, 0x2e, 0x15, 0x5f, 0x77, 0x3b, 0xe3, 0x99, 0xf3, 0x3c, 0x73, 0xce, 0x33, 0xe7, 0x9c,
	0x31, 0x80, 0xeb, 0x38, 0xc3, 0xc6, 0xc8, 0x75, 0x7c, 0x47, 0x5d, 0xb8, 0x3b, 0x3a, 0x76, 0x9d,
	0x06, 0x66, 0x33, 0xdd, 0xb5, 0xf5, 0x81, 0xe3, 0x0c, 0x2c, 0xa2, 0x1b, 0x23, 0x53, 0x37, 0x6c,
	0xdb, 0xf1, 0x0d, 0xdf, 0x74, 0x6c, 0x8f, 0x2f, 0x5e, 0xfb, 0xdf, 0xc0, 0xf4, 0x8f, 0x83, 0x6e,
	0xa3, 0xe7, 0x0c, 0xf5, 0x81, 0x63, 0x19, 0xf6, 0x40, 0x67, 0x3f, 0x74, 0x83, 0x23, 0x7d, 0xe4,
	0x3f, 0x1d, 0x11, 0x4f, 0x7f, 0xe2, 0x1a, 0xa3, 0x11, 0x71, 0x93, 0x8f, 0x70, 0xeb, 0x5d, 0x61,
	0xab, 0x65, 0x0c, 0x47, 0x86, 0xdb, 0xbf, 0x7e, 0xed, 0xfa, 0xae, 0x6e, 0x50, 0x78, 0xbd, 0xe5,
	0x0c, 0x87, 0x8e, 0xbd, 0x67, 0xbe, 0xaf, 0x63, 0xe2, 0x8d, 0x1c, 0xdb, 0x23, 0xfa, 0x83, 0x3d,
	0xdd, 0x0d, 0xbf, 0xb9, 0x09, 0xf4, 0x3a, 0x9c, 0xc6, 0x9d, 0x7d, 0x62, 0x11, 0x9f, 0x60, 0xf2,
	0x28, 0x20, 0x9e, 0xaf, 0x2e, 0xc3, 0x09, 0x7a, 0x96, 0xf6, 0xbe, 0xa6, 0x6c, 0x2a, 0xdb, 0x0b,
	0x38, 0x1c, 0xa9, 0x08, 0x4e, 0x7a, 0xc4, 0xf3, 0x4c, 0xc7, 0x3e, 0x70, 0xde, 0x23, 0xb6, 0x56,
	0xd9, 0x54, 0xb6, 0xe7, 0xb1, 0x34, 0x87, 0xfe, 0x0b, 0x8b, 0x89, 0x39, 0x0e, 0xa4, 0x6a, 0x30,
	0xeb, 0x05, 0xbd, 0x1e, 0xf1, 0x3c, 0x66, 0x70, 0x0e, 0x47, 0x43, 0xf4, 0x4d, 0x05, 0xe6, 0x70,
	0x07, 0x13, 0x2f, 0xb0, 0xc6, 0xc3, 0x6e, 0x00, 0x0c, 0x89, 0xdb, 0x3b, 0x36, 0x6c, 0xbf, 0xbd,
	0xcf, 0x40, 0x17, 0xb0, 0x30, 0x43, 0x69, 0xf9, 0xc4, 0x1d, 0x9a, 0xb6, 0x61, 0xb5, 0x9c, 0x3e,
	0xd1, 0xaa, 0x9c, 0x96, 0x38, 0xa7, 0xde, 0x84, 0x39, 0xcb, 0xe9, 0x31, 0xb7, 0x6b, 0xb5, 0x4d,
	0x65, 0xbb, 0xde, 0x5c, 0x6d, 0x48, 0x31, 0x6a, 0xe0, 0xce, 0x6b, 0xe1, 0x02, 0x1c, 0x2f, 0xa5,
	0x94, 0x3c, 0xdf, 0xf0, 0x03, 0x4f, 0x9b, 0xe1, 0x94, 0xf8, 0x48, 0x5d, 0x83, 0x39, 0x4a, 0xee,
	0x0d, 0x63, 0x48, 0xb4, 0x13, 0x0c, 0x2e, 0x1e, 0xab, 0x2a, 0xd4, 0x8e, 0x2c, 0x63, 0xa0, 0xcd,
	0xb1, 0x1d, 0xec, 0x5b, 0xbd, 0x0d, 0xf5, 0xde, 0xb1, 0xe1, 0x0e, 0x08, 0x0e, 0x2c, 0xe2, 0x69,
	0xb3, 0x9b, 0xd5, 0xed, 0x7a, 0x53, 0x4b, 0x33, 0x68, 0x61, 0xee, 0x09, 0x2c, 0x2e, 0x46, 0x16,
	0x9c, 0xc2, 0x9d, 0x37, 0x03, 0xe2, 0x3e, 0x8d, 0xe2, 0x93, 0x8e, 0x83, 0x92, 0x8d, 0x83, 0xe0,
	0xcc, 0x4a, 0x81, 0x33, 0xab, 0x69, 0x67, 0xa2, 0xb7, 0xa9, 0x1c, 0x42, 0xb4, 0xb2, 0xf0, 0xa9,
	0x57, 0x61, 0x86, 0x9a, 0xf5, 0xb4, 0x0a, 0x3b, 0xd0, 0x4a, 0xc6, 0xa5, 0xe1, 0x79, 0xf8, 0x2a,
	0xf4, 0xbd, 0x42, 0x8d, 0xb7, 0x5c, 0x62, 0x24, 0x5a, 0x4b, 0x07, 0x4f, 0xc9, 0x09, 0xde, 0x04,
	0xba, 0x93, 0x02, 0x5c, 0x9d, 0x3c, 0xc0, 0x62, 0x20, 0x6b, 0x72, 0x20, 0xd1, 0x3e, 0x95, 0x72,
	0xc4, 0x36, 0xf4, 0xc5, 0x38, 0x8d, 0x0a, 0x3e, 0xaa, 0xc8, 0x12, 0xff, 0xb5, 0x42, 0x0f, 0x7d,
	0x38, 0xea, 0x0b, 0x87, 0xbe, 0x93, 0x13, 0xc0, 0x7a, 0x73, 0xbd, 0xc1, 0xd3, 0x44, 0x23, 0xba,
	0xfd, 0x8d, 0x8e, 0xef, 0x9a, 0xf6, 0xe0, 0x2d, 0xc3, 0x0a, 0x48, 0xea, 0xb8, 0xbb, 0x52, 0x78,
	0xf3, 0xf6, 0x1e, 0xb6, 0x6d, 0xff, 0x46, 0x93, 0xef, 0x8d, 0x58, 0xde, 0xc9, 0xb9, 0x29, 0xa5,
	0xb8, 0xaf, 0xe2, 0x1e, 0xed, 0x4a, 0xf7, 0xa8, 0x94, 0x6e, 0x78, 0xcb, 0x6e, 0x09, 0xc1, 0x99,
	0x9d, 0x80, 0x6a, 0x12, 0x3a, 0x96, 0x85, 0x22, 0x9f, 0x67, 0x65, 0x9c, 0x0a, 0xd1, 0x7d, 0x80,
	0x84, 0xb5, 0xba, 0x0e, 0xf3, 0x96, 0x63, 0x0f, 0x4c, 0x3f, 0x88, 0xe5, 0x98, 0x4c, 0x50, 0xc1,
	0x58, 0x86, 0xcf, 0x7f, 0xe4, 0x3a, 0x8c, 0xc7, 0xe8, 0x07, 0x05, 0xce, 0xe1, 0xce, 0x41, 0xe8,
	0xaf, 0x3d, 0xd3, 0xee, 0x4f, 0x73, 0x63, 0xd3, 0x37, 0xa1, 0x52, 0x92, 0xc6, 0xaa, 0x53, 0xa5,
	0xb1, 0x50, 0x2d, 0x35, 0x51, 0xb5, 0xa8, 0x09, 0xcb, 0x69, 0xbe, 0xa5, 0x29, 0xfb, 0x10, 0x56,
	0x92, 0x3d, 0x87, 0x76, 0x57, 0x38, 0xe5, 0x1f, 0xa9, 0x1b, 0xbb, 0xa0, 0x65, 0xcd, 0x96, 0x92,
	0xf9, 0x4d, 0x81, 0xf9, 0x38, 0x6d, 0xa6, 0x72, 0x9b, 0x92, 0x29, 0x14, 0x4b, 0x30, 0x83, 0x5b,
	0xb8, 0xbd, 0xcf, 0xc4, 0xb4, 0x80, 0xf9, 0x40, 0x5d, 0x84, 0xea, 0x11, 0xe1, 0xee, 0xae, 0x60,
	0xfa, 0x49, 0xd7, 0x79, 0xbe, 0xe1, 0xfa, 0x61, 0x25, 0xe1, 0x03, 0xba, 0x8e, 0xd8, 0xfd, 0x30,
	0x4b, 0xd0, 0x4f, 0xaa, 0x05, 0xd3, 0xf6, 0x89, 0xfb, 0xd8, 0xb0, 0xc2, 0xfa, 0x10, 0x8f, 0xe9,
	0x99, 0xa3, 0xef, 0x43, 0xdb, 0xf4, 0x59, 0x95, 0x58, 0xc0, 0xd2, 0x9c, 0xe0, 0xaf, 0x39, 0xc9,
	0x5f, 0x51, 0x05, 0x99, 0x17, 0x2a, 0x88, 0x0a, 0x35, 0x9b, 0xde, 0x03, 0x60, 0xf0, 0xec, 0x1b,
	0x3d, 0x57, 0x60, 0x11, 0xb7, 0xb0, 0x5c, 0xbc, 0xcb, 0x9c, 0x30, 0x49, 0x32, 0xcd, 0x77, 0xd4,
	0x18, 0xba, 0xe8, 0x2a, 0x9c, 0x11, 0x58, 0x94, 0xc6, 0xec, 0x63, 0x5a, 0x05, 0x5a, 0x58, 0xaa,
	0x68, 0x31, 0xa0, 0x22, 0x02, 0xa6, 0xa9, 0xd6, 0x72, 0xa8, 0x96, 0x35, 0x07, 0x09, 0xe9, 0xaa,
	0x44, 0xfa, 0x21, 0x73, 0xdd, 0xa4, 0x85, 0xae, 0x09, 0xb3, 0x2e, 0xd3, 0x58, 0x54, 0xea, 0xc6,
	0xd7, 0xee, 0x68, 0x21, 0xfa, 0xac, 0xc2, 0x20, 0xe4, 0xcc, 0xff, 0x72, 0x12, 0x4d, 0x3b, 0x62,
	0x3e, 0xc7, 0x11, 0x7f, 0x4b, 0x19, 0x67, 0x24, 0xcb, 0xb5, 0x32, 0x3e, 0x33, 0xa7, 0xb4, 0xf2,
	0x2d, 0xf7, 0xa1, 0xdc, 0x32, 0x2c, 0xc1, 0x8c, 0xdb, 0x73, 0xdb, 0xfb, 0x5a, 0x9d, 0xfb, 0x88,
	0x0d, 0x26, 0x4a, 0xb1, 0x7f, 0x9d, 0x8f, 0xe4, 0xb8, 0xcf, 0x16, 0xc8, 0xf4, 0xe5, 0x52, 0xc1,
	0x77, 0xb4, 0xf4, 0xb4, 0xf0, 0x9e, 0xe1, 0xf7, 0x8e, 0x33, 0x0d, 0x56, 0xa9, 0x5f, 0x5e, 0xf2,
	0x12, 0xa9, 0x37, 0x61, 0xc6, 0x65, 0x0d, 0x6d, 0x8d, 0x5d, 0x8a, 0x8b, 0xd9, 0x4b, 0x21, 0x71,
	0xc1, 0x7c, 0x35, 0x2b, 0x3b, 0x29, 0xae, 0xa5, 0x4a, 0x68, 0x33, 0xe1, 0x4c, 0xba, 0x9c, 0xf5,
	0x75, 0xa4, 0xe7, 0xf4, 0x49, 0x7c, 0x9e, 0x78, 0x8c, 0x5e, 0x28, 0xb0, 0x8a, 0x3b, 0x07, 0xae,
	0x61, 0x7b, 0x46, 0x8f, 0xd6, 0xc7, 0x3d, 0x32, 0x30, 0xed, 0x57, 0xd1, 0x5c, 0xb7, 0xe1, 0x34,
	0xfd, 0x6a, 0x09, 0xad, 0x7e, 0x75, 0x32, 0xcf, 0xa4, 0xf7, 0xd1, 0xdc, 0xbe, 0x96, 0x47, 0xb2,
	0xf4, 0xe4, 0x5b, 0xb0, 0xe0, 0x27, 0xbb, 0x62, 0x8a, 0xf2, 0xa4, 0xac, 0xfb, 0x9a, 0xa0, 0x7b,
	0x7a, 0x3f, 0x6a, 0xf1, 0xfd, 0x40, 0xcf, 0xe0, 0xbc, 0xc4, 0xa2, 0x13, 0x78, 0x23, 0x32, 0x5d,
	0x5f, 0x33, 0xce, 0x59, 0x19, 0xa2, 0xd5, 0x1c, 0xa2, 0xe8, 0x16, 0xac, 0xe7, 0x13, 0x28, 0x55,
	0xcc, 0x57, 0x0a, 0xeb, 0x54, 0x92, 0xad, 0xf7, 0xfe, 0x44, 0xde, 0xa9, 0x2b, 0x55, 0xcb, 0xbc,
	0xb3, 0x78, 0xbf, 0x93, 0x22, 0x57, 0x7a, 0xa6, 0x1f, 0x2b, 0xf0, 0x1f, 0x69, 0x5b, 0xa8, 0x22,
	0xc7, 0x19, 0xde, 0x27, 0x53, 0x5d, 0xf9, 0x7f, 0x5e, 0x2a, 0xcc, 0xf8, 0x7d, 0x3e, 0xcf, 0xef,
	0x51, 0xc2, 0x84, 0x24, 0x61, 0xa2, 0xff, 0x03, 0x2a, 0x72, 0x5a, 0xa9, 0xd7, 0x7f, 0x52, 0x60,
	0x53, 0x32, 0xc0, 0xdb, 0x86, 0xe9, 0x9d, 0x3e, 0xd9, 0x11, 0x9a, 0xb0, 0x24, 0x4c, 0x84, 0x30,
	0xb1, 0x0c, 0x73, 0x7f, 0x1b, 0xdb, 0x9b, 0x3d, 0x57, 0x52, 0x82, 0x91, 0xa9, 0x97, 0x66, 0x93,
	0x7b, 0xfc, 0x09, 0x76, 0x9f, 0x90, 0xa8, 0xf3, 0xb9, 0x92, 0x79, 0x70, 0x1c, 0x64, 0x08, 0x85,
	0xad, 0x50, 0xbc, 0x15, 0x7d, 0x5d, 0x4d, 0x65, 0x33, 0x69, 0xe1, 0xd8, 0x13, 0x2b, 0x05, 0x27,
	0xce, 0x0a, 0x78, 0x03, 0xa0, 0xc7, 0x22, 0x7b, 0x60, 0x0e, 0x89, 0x76, 0x92, 0x0b, 0x2b, 0x99,
	0xa1, 0xa7, 0x24, 0x76, 0x9f, 0xfd, 0xb8, 0xc0, 0x7e, 0x8c, 0x86, 0xea, 0x65, 0x38, 0x75, 0x44,
	0xc8, 0x03, 0xe2, 0xb6, 0x23, 0x61, 0xd7, 0x99, 0xd9, 0xd4, 0xec, 0xbf, 0xf7, 0x8a, 0x34, 0x5f,
	0x9c, 0x86, 0x3a, 0xf5, 0x6d, 0x87, 0xb8, 0x8f, 0xcd, 0x1e, 0x51, 0x9d, 0xe4, 0x31, 0x4a, 0xdf,
	0x85, 0xea, 0x56, 0x36, 0xea, 0xd9, 0x67, 0xee, 0x5a, 0xf4, 0x18, 0x8d, 0xff, 0x78, 0x6c, 0x44,
	0x12, 0x43, 0x1b, 0x1f, 0xfd, 0xfc, 0xcb, 0xe7, 0x15, 0x0d, 0x9d, 0xd5, 0x29, 0x57, 0x3d, 0x32,
	0xae, 0xd3, 0x87, 0xde, 0x6d, 0x65, 0x47, 0x0d, 0xe0, 0x94, 0x2f, 0xbd, 0xfe, 0xd4, 0xcb, 0x63,
	0x21, 0xa5, 0x57, 0x67, 0x11, 0xe8, 0x26, 0x03, 0x5d, 0x43, 0xe7, 0x52, 0xa0, 0x81, 0x1d, 0xc1,
	0x3e, 0x8c, 0x34, 0x43, 0x51, 0xd4, 0x8d, 0x0c, 0xa4, 0x54, 0xa5, 0x8b, 0xa0, 0x56, 0x18, 0xd4,
	0x19, 0x74, 0x92, 0x43, 0x71, 0xa3, 0x21, 0x42, 0xc0, 0xdb, 0xdd, 0x7c, 0x04, 0xe9, 0x7d, 0x30,
	0x05, 0x02, 0x37, 0x4a, 0x11, 0x4c, 0x80, 0x3e, 0x7f, 0x7c, 0xe5, 0x23, 0x48, 0xef, 0xc3, 0x09,
	0xdc, 0xb5, 0x16, 0xba, 0x8b, 0x1b, 0xd5, 0x3f, 0xe0, 0xe2, 0xfa, 0x90, 0x42, 0xbd, 0x03, 0xf3,
	0x8f, 0xa2, 0x04, 0xa2, 0x5e, 0xc8, 0x20, 0x89, 0x6f, 0xba, 0x22, 0xa0, 0x65, 0x06, 0xb4, 0x88,
	0xea, 0x1c, 0x88, 0x99, 0xa4, 0xe6, 0x9f, 0xc0, 0x52, 0x12, 0x8d, 0xa4, 0x1b, 0x52, 0xcb, 0xda,
	0xa7, 0x22, 0xac, 0x4b, 0x0c, 0xeb, 0x02, 0xd2, 0xc2, 0xc0, 0x30, 0xab, 0xef, 0xd2, 0x46, 0x54,
	0x08, 0xd2, 0xa7, 0x0a, 0xac, 0x76, 0x85, 0x7e, 0x54, 0x86, 0xdf, 0xca, 0xc2, 0x67, 0x1b, 0xed,
	0x22, 0x0e, 0xdb, 0x8c, 0x03, 0x42, 0x17, 0xb2, 0x1c, 0x04, 0xd4, 0xd0, 0x03, 0x89, 0x5a, 0x8a,
	0x3d, 0x30, 0xb1, 0x70, 0x0a, 0x3c, 0x90, 0x88, 0xc8, 0x87, 0xb3, 0x71, 0x64, 0x05, 0xdc, 0x8d,
	0x2c, 0xee, 0xa4, 0x41, 0x46, 0x0c, 0x76, 0x1d, 0xad, 0x64, 0x61, 0xc5, 0x80, 0x27, 0xd2, 0x2d,
	0x3e, 0xee, 0xc4, 0x2a, 0x2e, 0x38, 0x2e, 0xc7, 0xa2, 0xc0, 0xcf, 0x60, 0x89, 0xfe, 0x9a, 0xee,
	0xaf, 0xd5, 0xed, 0xa2, 0xea, 0x26, 0xbe, 0x13, 0xa6, 0x38, 0xb9, 0x90, 0x7d, 0xf5, 0x2e, 0x35,
	0x41, 0x09, 0x7c, 0xa2, 0xc0, 0x72, 0x8a, 0x41, 0xd8, 0xda, 0xaa, 0x3b, 0x45, 0x1c, 0xe4, 0x06,
	0xbc, 0x88, 0xc5, 0x16, 0x63, 0xb1, 0x81, 0x56, 0xb3, 0x2c, 0x3c, 0x6e, 0x84, 0xf2, 0x78, 0x0a,
	0x6a, 0x8a, 0xc6, 0xbd, 0xfc, 0xdc, 0x9b, 0xd7, 0x47, 0x4f, 0x93, 0x7b, 0x05, 0xf8, 0x10, 0xfa,
	0x4b, 0x05, 0xd6, 0x53, 0xd8, 0x52, 0x67, 0xa6, 0x5e, 0x2b, 0x62, 0x91, 0xd7, 0xf9, 0x16, 0xf1,
	0xd9, 0x61, 0x7c, 0xb6, 0xd0, 0xc5, 0x2c, 0x9f, 0x9e, 0x68, 0x8a, 0x32, 0xfb, 0x42, 0x81, 0xf3,
	0x29, 0x66, 0x62, 0xdf, 0xa4, 0xea, 0x45, 0xc4, 0x72, 0x9a, 0xc3, 0x22, 0x5e, 0x57, 0x18, 0xaf,
	0x4b, 0x68, 0x23, 0xcb, 0xeb, 0x91, 0x60, 0xe9, 0xb6, 0xb2, 0xd3, 0x3d, 0xc1, 0xfe, 0xf5, 0xbe,
	0xf1, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xa7, 0x99, 0x6f, 0x6a, 0x1c, 0x00, 0x00,
}
